// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// UpdateStories update stories
//
// swagger:model UpdateStories
type UpdateStories struct {

	// The ID of the story that the stories are to be moved below.
	AfterID int64 `json:"after_id,omitempty"`

	// If the Stories should be archived or not.
	Archived bool `json:"archived,omitempty"`

	// The ID of the story that the stories are to be moved before.
	BeforeID int64 `json:"before_id,omitempty"`

	// The due date of the story.
	// Format: date-time
	Deadline *strfmt.DateTime `json:"deadline,omitempty"`

	// The ID of the epic the story belongs to.
	EpicID *int64 `json:"epic_id,omitempty"`

	// The numeric point estimate of the story. Can also be null, which means unestimated.
	Estimate *int64 `json:"estimate,omitempty"`

	// The UUIDs of the new followers to be added.
	// Unique: true
	FollowerIdsAdd []strfmt.UUID `json:"follower_ids_add"`

	// The UUIDs of the followers to be removed.
	// Unique: true
	FollowerIdsRemove []strfmt.UUID `json:"follower_ids_remove"`

	// The ID of the iteration the story belongs to.
	IterationID *int64 `json:"iteration_id,omitempty"`

	// An array of labels to be added.
	LabelsAdd []*CreateLabelParams `json:"labels_add"`

	// An array of labels to be removed.
	LabelsRemove []*CreateLabelParams `json:"labels_remove"`

	// move to
	// Enum: [first last]
	MoveTo string `json:"move_to,omitempty"`

	// The UUIDs of the new owners to be added.
	// Unique: true
	OwnerIdsAdd []strfmt.UUID `json:"owner_ids_add"`

	// The UUIDs of the owners to be removed.
	// Unique: true
	OwnerIdsRemove []strfmt.UUID `json:"owner_ids_remove"`

	// The ID of the Project the Stories should belong to.
	ProjectID int64 `json:"project_id,omitempty"`

	// The ID of the member that requested the story.
	// Format: uuid
	RequestedByID strfmt.UUID `json:"requested_by_id,omitempty"`

	// The unique IDs of the Stories you wish to update.
	// Required: true
	StoryIds []int64 `json:"story_ids"`

	// The type of story (feature, bug, chore).
	// Enum: [bug chore feature]
	StoryType string `json:"story_type,omitempty"`

	// The ID of the workflow state to put the stories in.
	WorkflowStateID int64 `json:"workflow_state_id,omitempty"`
}

// Validate validates this update stories
func (m *UpdateStories) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDeadline(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFollowerIdsAdd(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFollowerIdsRemove(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLabelsAdd(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLabelsRemove(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMoveTo(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOwnerIdsAdd(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOwnerIdsRemove(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRequestedByID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStoryIds(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStoryType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UpdateStories) validateDeadline(formats strfmt.Registry) error {

	if swag.IsZero(m.Deadline) { // not required
		return nil
	}

	if err := validate.FormatOf("deadline", "body", "date-time", m.Deadline.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *UpdateStories) validateFollowerIdsAdd(formats strfmt.Registry) error {

	if swag.IsZero(m.FollowerIdsAdd) { // not required
		return nil
	}

	if err := validate.UniqueItems("follower_ids_add", "body", m.FollowerIdsAdd); err != nil {
		return err
	}

	for i := 0; i < len(m.FollowerIdsAdd); i++ {

		if err := validate.FormatOf("follower_ids_add"+"."+strconv.Itoa(i), "body", "uuid", m.FollowerIdsAdd[i].String(), formats); err != nil {
			return err
		}

	}

	return nil
}

func (m *UpdateStories) validateFollowerIdsRemove(formats strfmt.Registry) error {

	if swag.IsZero(m.FollowerIdsRemove) { // not required
		return nil
	}

	if err := validate.UniqueItems("follower_ids_remove", "body", m.FollowerIdsRemove); err != nil {
		return err
	}

	for i := 0; i < len(m.FollowerIdsRemove); i++ {

		if err := validate.FormatOf("follower_ids_remove"+"."+strconv.Itoa(i), "body", "uuid", m.FollowerIdsRemove[i].String(), formats); err != nil {
			return err
		}

	}

	return nil
}

func (m *UpdateStories) validateLabelsAdd(formats strfmt.Registry) error {

	if swag.IsZero(m.LabelsAdd) { // not required
		return nil
	}

	for i := 0; i < len(m.LabelsAdd); i++ {
		if swag.IsZero(m.LabelsAdd[i]) { // not required
			continue
		}

		if m.LabelsAdd[i] != nil {
			if err := m.LabelsAdd[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("labels_add" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *UpdateStories) validateLabelsRemove(formats strfmt.Registry) error {

	if swag.IsZero(m.LabelsRemove) { // not required
		return nil
	}

	for i := 0; i < len(m.LabelsRemove); i++ {
		if swag.IsZero(m.LabelsRemove[i]) { // not required
			continue
		}

		if m.LabelsRemove[i] != nil {
			if err := m.LabelsRemove[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("labels_remove" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

var updateStoriesTypeMoveToPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["first","last"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		updateStoriesTypeMoveToPropEnum = append(updateStoriesTypeMoveToPropEnum, v)
	}
}

const (

	// UpdateStoriesMoveToFirst captures enum value "first"
	UpdateStoriesMoveToFirst string = "first"

	// UpdateStoriesMoveToLast captures enum value "last"
	UpdateStoriesMoveToLast string = "last"
)

// prop value enum
func (m *UpdateStories) validateMoveToEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, updateStoriesTypeMoveToPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *UpdateStories) validateMoveTo(formats strfmt.Registry) error {

	if swag.IsZero(m.MoveTo) { // not required
		return nil
	}

	// value enum
	if err := m.validateMoveToEnum("move_to", "body", m.MoveTo); err != nil {
		return err
	}

	return nil
}

func (m *UpdateStories) validateOwnerIdsAdd(formats strfmt.Registry) error {

	if swag.IsZero(m.OwnerIdsAdd) { // not required
		return nil
	}

	if err := validate.UniqueItems("owner_ids_add", "body", m.OwnerIdsAdd); err != nil {
		return err
	}

	for i := 0; i < len(m.OwnerIdsAdd); i++ {

		if err := validate.FormatOf("owner_ids_add"+"."+strconv.Itoa(i), "body", "uuid", m.OwnerIdsAdd[i].String(), formats); err != nil {
			return err
		}

	}

	return nil
}

func (m *UpdateStories) validateOwnerIdsRemove(formats strfmt.Registry) error {

	if swag.IsZero(m.OwnerIdsRemove) { // not required
		return nil
	}

	if err := validate.UniqueItems("owner_ids_remove", "body", m.OwnerIdsRemove); err != nil {
		return err
	}

	for i := 0; i < len(m.OwnerIdsRemove); i++ {

		if err := validate.FormatOf("owner_ids_remove"+"."+strconv.Itoa(i), "body", "uuid", m.OwnerIdsRemove[i].String(), formats); err != nil {
			return err
		}

	}

	return nil
}

func (m *UpdateStories) validateRequestedByID(formats strfmt.Registry) error {

	if swag.IsZero(m.RequestedByID) { // not required
		return nil
	}

	if err := validate.FormatOf("requested_by_id", "body", "uuid", m.RequestedByID.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *UpdateStories) validateStoryIds(formats strfmt.Registry) error {

	if err := validate.Required("story_ids", "body", m.StoryIds); err != nil {
		return err
	}

	return nil
}

var updateStoriesTypeStoryTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["bug","chore","feature"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		updateStoriesTypeStoryTypePropEnum = append(updateStoriesTypeStoryTypePropEnum, v)
	}
}

const (

	// UpdateStoriesStoryTypeBug captures enum value "bug"
	UpdateStoriesStoryTypeBug string = "bug"

	// UpdateStoriesStoryTypeChore captures enum value "chore"
	UpdateStoriesStoryTypeChore string = "chore"

	// UpdateStoriesStoryTypeFeature captures enum value "feature"
	UpdateStoriesStoryTypeFeature string = "feature"
)

// prop value enum
func (m *UpdateStories) validateStoryTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, updateStoriesTypeStoryTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *UpdateStories) validateStoryType(formats strfmt.Registry) error {

	if swag.IsZero(m.StoryType) { // not required
		return nil
	}

	// value enum
	if err := m.validateStoryTypeEnum("story_type", "body", m.StoryType); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *UpdateStories) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UpdateStories) UnmarshalBinary(b []byte) error {
	var res UpdateStories
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
