// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/bateau-eng/chapi/pkg/models"
)

// NewDeleteAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactionsParams creates a new DeleteAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactionsParams object
// with the default values initialized.
func NewDeleteAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactionsParams() *DeleteAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactionsParams {
	var ()
	return &DeleteAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactionsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactionsParamsWithTimeout creates a new DeleteAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactionsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactionsParamsWithTimeout(timeout time.Duration) *DeleteAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactionsParams {
	var ()
	return &DeleteAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactionsParams{

		timeout: timeout,
	}
}

// NewDeleteAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactionsParamsWithContext creates a new DeleteAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactionsParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactionsParamsWithContext(ctx context.Context) *DeleteAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactionsParams {
	var ()
	return &DeleteAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactionsParams{

		Context: ctx,
	}
}

// NewDeleteAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactionsParamsWithHTTPClient creates a new DeleteAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactionsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactionsParamsWithHTTPClient(client *http.Client) *DeleteAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactionsParams {
	var ()
	return &DeleteAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactionsParams{
		HTTPClient: client,
	}
}

/*DeleteAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactionsParams contains all the parameters to send to the API endpoint
for the delete API v3 stories story public ID comments comment public ID reactions operation typically these are written to a http.Request
*/
type DeleteAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactionsParams struct {

	/*CreateOrDeleteReaction*/
	CreateOrDeleteReaction *models.CreateOrDeleteReaction
	/*CommentPublicID
	  The ID of the Comment.

	*/
	CommentPublicID int64
	/*StoryPublicID
	  The ID of the Story that the Comment is in.

	*/
	StoryPublicID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete API v3 stories story public ID comments comment public ID reactions params
func (o *DeleteAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactionsParams) WithTimeout(timeout time.Duration) *DeleteAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete API v3 stories story public ID comments comment public ID reactions params
func (o *DeleteAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete API v3 stories story public ID comments comment public ID reactions params
func (o *DeleteAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactionsParams) WithContext(ctx context.Context) *DeleteAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete API v3 stories story public ID comments comment public ID reactions params
func (o *DeleteAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete API v3 stories story public ID comments comment public ID reactions params
func (o *DeleteAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactionsParams) WithHTTPClient(client *http.Client) *DeleteAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactionsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete API v3 stories story public ID comments comment public ID reactions params
func (o *DeleteAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactionsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCreateOrDeleteReaction adds the createOrDeleteReaction to the delete API v3 stories story public ID comments comment public ID reactions params
func (o *DeleteAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactionsParams) WithCreateOrDeleteReaction(createOrDeleteReaction *models.CreateOrDeleteReaction) *DeleteAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactionsParams {
	o.SetCreateOrDeleteReaction(createOrDeleteReaction)
	return o
}

// SetCreateOrDeleteReaction adds the createOrDeleteReaction to the delete API v3 stories story public ID comments comment public ID reactions params
func (o *DeleteAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactionsParams) SetCreateOrDeleteReaction(createOrDeleteReaction *models.CreateOrDeleteReaction) {
	o.CreateOrDeleteReaction = createOrDeleteReaction
}

// WithCommentPublicID adds the commentPublicID to the delete API v3 stories story public ID comments comment public ID reactions params
func (o *DeleteAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactionsParams) WithCommentPublicID(commentPublicID int64) *DeleteAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactionsParams {
	o.SetCommentPublicID(commentPublicID)
	return o
}

// SetCommentPublicID adds the commentPublicId to the delete API v3 stories story public ID comments comment public ID reactions params
func (o *DeleteAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactionsParams) SetCommentPublicID(commentPublicID int64) {
	o.CommentPublicID = commentPublicID
}

// WithStoryPublicID adds the storyPublicID to the delete API v3 stories story public ID comments comment public ID reactions params
func (o *DeleteAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactionsParams) WithStoryPublicID(storyPublicID int64) *DeleteAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactionsParams {
	o.SetStoryPublicID(storyPublicID)
	return o
}

// SetStoryPublicID adds the storyPublicId to the delete API v3 stories story public ID comments comment public ID reactions params
func (o *DeleteAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactionsParams) SetStoryPublicID(storyPublicID int64) {
	o.StoryPublicID = storyPublicID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.CreateOrDeleteReaction != nil {
		if err := r.SetBodyParam(o.CreateOrDeleteReaction); err != nil {
			return err
		}
	}

	// path param comment-public-id
	if err := r.SetPathParam("comment-public-id", swag.FormatInt64(o.CommentPublicID)); err != nil {
		return err
	}

	// path param story-public-id
	if err := r.SetPathParam("story-public-id", swag.FormatInt64(o.StoryPublicID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
