// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteAPIV3IterationsIterationPublicIDReader is a Reader for the DeleteAPIV3IterationsIterationPublicID structure.
type DeleteAPIV3IterationsIterationPublicIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAPIV3IterationsIterationPublicIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteAPIV3IterationsIterationPublicIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteAPIV3IterationsIterationPublicIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteAPIV3IterationsIterationPublicIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewDeleteAPIV3IterationsIterationPublicIDUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteAPIV3IterationsIterationPublicIDNoContent creates a DeleteAPIV3IterationsIterationPublicIDNoContent with default headers values
func NewDeleteAPIV3IterationsIterationPublicIDNoContent() *DeleteAPIV3IterationsIterationPublicIDNoContent {
	return &DeleteAPIV3IterationsIterationPublicIDNoContent{}
}

/*DeleteAPIV3IterationsIterationPublicIDNoContent handles this case with default header values.

No Content
*/
type DeleteAPIV3IterationsIterationPublicIDNoContent struct {
}

func (o *DeleteAPIV3IterationsIterationPublicIDNoContent) Error() string {
	return fmt.Sprintf("[DELETE /api/v3/iterations/{iteration-public-id}][%d] deleteApiV3IterationsIterationPublicIdNoContent ", 204)
}

func (o *DeleteAPIV3IterationsIterationPublicIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteAPIV3IterationsIterationPublicIDBadRequest creates a DeleteAPIV3IterationsIterationPublicIDBadRequest with default headers values
func NewDeleteAPIV3IterationsIterationPublicIDBadRequest() *DeleteAPIV3IterationsIterationPublicIDBadRequest {
	return &DeleteAPIV3IterationsIterationPublicIDBadRequest{}
}

/*DeleteAPIV3IterationsIterationPublicIDBadRequest handles this case with default header values.

Schema mismatch
*/
type DeleteAPIV3IterationsIterationPublicIDBadRequest struct {
}

func (o *DeleteAPIV3IterationsIterationPublicIDBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /api/v3/iterations/{iteration-public-id}][%d] deleteApiV3IterationsIterationPublicIdBadRequest ", 400)
}

func (o *DeleteAPIV3IterationsIterationPublicIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteAPIV3IterationsIterationPublicIDNotFound creates a DeleteAPIV3IterationsIterationPublicIDNotFound with default headers values
func NewDeleteAPIV3IterationsIterationPublicIDNotFound() *DeleteAPIV3IterationsIterationPublicIDNotFound {
	return &DeleteAPIV3IterationsIterationPublicIDNotFound{}
}

/*DeleteAPIV3IterationsIterationPublicIDNotFound handles this case with default header values.

Resource does not exist
*/
type DeleteAPIV3IterationsIterationPublicIDNotFound struct {
}

func (o *DeleteAPIV3IterationsIterationPublicIDNotFound) Error() string {
	return fmt.Sprintf("[DELETE /api/v3/iterations/{iteration-public-id}][%d] deleteApiV3IterationsIterationPublicIdNotFound ", 404)
}

func (o *DeleteAPIV3IterationsIterationPublicIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteAPIV3IterationsIterationPublicIDUnprocessableEntity creates a DeleteAPIV3IterationsIterationPublicIDUnprocessableEntity with default headers values
func NewDeleteAPIV3IterationsIterationPublicIDUnprocessableEntity() *DeleteAPIV3IterationsIterationPublicIDUnprocessableEntity {
	return &DeleteAPIV3IterationsIterationPublicIDUnprocessableEntity{}
}

/*DeleteAPIV3IterationsIterationPublicIDUnprocessableEntity handles this case with default header values.

Unprocessable
*/
type DeleteAPIV3IterationsIterationPublicIDUnprocessableEntity struct {
}

func (o *DeleteAPIV3IterationsIterationPublicIDUnprocessableEntity) Error() string {
	return fmt.Sprintf("[DELETE /api/v3/iterations/{iteration-public-id}][%d] deleteApiV3IterationsIterationPublicIdUnprocessableEntity ", 422)
}

func (o *DeleteAPIV3IterationsIterationPublicIDUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
