// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteAPIV3StoriesBulkReader is a Reader for the DeleteAPIV3StoriesBulk structure.
type DeleteAPIV3StoriesBulkReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAPIV3StoriesBulkReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteAPIV3StoriesBulkNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteAPIV3StoriesBulkBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteAPIV3StoriesBulkNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewDeleteAPIV3StoriesBulkUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteAPIV3StoriesBulkNoContent creates a DeleteAPIV3StoriesBulkNoContent with default headers values
func NewDeleteAPIV3StoriesBulkNoContent() *DeleteAPIV3StoriesBulkNoContent {
	return &DeleteAPIV3StoriesBulkNoContent{}
}

/*DeleteAPIV3StoriesBulkNoContent handles this case with default header values.

No Content
*/
type DeleteAPIV3StoriesBulkNoContent struct {
}

func (o *DeleteAPIV3StoriesBulkNoContent) Error() string {
	return fmt.Sprintf("[DELETE /api/v3/stories/bulk][%d] deleteApiV3StoriesBulkNoContent ", 204)
}

func (o *DeleteAPIV3StoriesBulkNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteAPIV3StoriesBulkBadRequest creates a DeleteAPIV3StoriesBulkBadRequest with default headers values
func NewDeleteAPIV3StoriesBulkBadRequest() *DeleteAPIV3StoriesBulkBadRequest {
	return &DeleteAPIV3StoriesBulkBadRequest{}
}

/*DeleteAPIV3StoriesBulkBadRequest handles this case with default header values.

Schema mismatch
*/
type DeleteAPIV3StoriesBulkBadRequest struct {
}

func (o *DeleteAPIV3StoriesBulkBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /api/v3/stories/bulk][%d] deleteApiV3StoriesBulkBadRequest ", 400)
}

func (o *DeleteAPIV3StoriesBulkBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteAPIV3StoriesBulkNotFound creates a DeleteAPIV3StoriesBulkNotFound with default headers values
func NewDeleteAPIV3StoriesBulkNotFound() *DeleteAPIV3StoriesBulkNotFound {
	return &DeleteAPIV3StoriesBulkNotFound{}
}

/*DeleteAPIV3StoriesBulkNotFound handles this case with default header values.

Resource does not exist
*/
type DeleteAPIV3StoriesBulkNotFound struct {
}

func (o *DeleteAPIV3StoriesBulkNotFound) Error() string {
	return fmt.Sprintf("[DELETE /api/v3/stories/bulk][%d] deleteApiV3StoriesBulkNotFound ", 404)
}

func (o *DeleteAPIV3StoriesBulkNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteAPIV3StoriesBulkUnprocessableEntity creates a DeleteAPIV3StoriesBulkUnprocessableEntity with default headers values
func NewDeleteAPIV3StoriesBulkUnprocessableEntity() *DeleteAPIV3StoriesBulkUnprocessableEntity {
	return &DeleteAPIV3StoriesBulkUnprocessableEntity{}
}

/*DeleteAPIV3StoriesBulkUnprocessableEntity handles this case with default header values.

Unprocessable
*/
type DeleteAPIV3StoriesBulkUnprocessableEntity struct {
}

func (o *DeleteAPIV3StoriesBulkUnprocessableEntity) Error() string {
	return fmt.Sprintf("[DELETE /api/v3/stories/bulk][%d] deleteApiV3StoriesBulkUnprocessableEntity ", 422)
}

func (o *DeleteAPIV3StoriesBulkUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
