// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteAPIV3CategoriesCategoryPublicIDReader is a Reader for the DeleteAPIV3CategoriesCategoryPublicID structure.
type DeleteAPIV3CategoriesCategoryPublicIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAPIV3CategoriesCategoryPublicIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteAPIV3CategoriesCategoryPublicIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteAPIV3CategoriesCategoryPublicIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteAPIV3CategoriesCategoryPublicIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewDeleteAPIV3CategoriesCategoryPublicIDUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteAPIV3CategoriesCategoryPublicIDNoContent creates a DeleteAPIV3CategoriesCategoryPublicIDNoContent with default headers values
func NewDeleteAPIV3CategoriesCategoryPublicIDNoContent() *DeleteAPIV3CategoriesCategoryPublicIDNoContent {
	return &DeleteAPIV3CategoriesCategoryPublicIDNoContent{}
}

/*DeleteAPIV3CategoriesCategoryPublicIDNoContent handles this case with default header values.

No Content
*/
type DeleteAPIV3CategoriesCategoryPublicIDNoContent struct {
}

func (o *DeleteAPIV3CategoriesCategoryPublicIDNoContent) Error() string {
	return fmt.Sprintf("[DELETE /api/v3/categories/{category-public-id}][%d] deleteApiV3CategoriesCategoryPublicIdNoContent ", 204)
}

func (o *DeleteAPIV3CategoriesCategoryPublicIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteAPIV3CategoriesCategoryPublicIDBadRequest creates a DeleteAPIV3CategoriesCategoryPublicIDBadRequest with default headers values
func NewDeleteAPIV3CategoriesCategoryPublicIDBadRequest() *DeleteAPIV3CategoriesCategoryPublicIDBadRequest {
	return &DeleteAPIV3CategoriesCategoryPublicIDBadRequest{}
}

/*DeleteAPIV3CategoriesCategoryPublicIDBadRequest handles this case with default header values.

Schema mismatch
*/
type DeleteAPIV3CategoriesCategoryPublicIDBadRequest struct {
}

func (o *DeleteAPIV3CategoriesCategoryPublicIDBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /api/v3/categories/{category-public-id}][%d] deleteApiV3CategoriesCategoryPublicIdBadRequest ", 400)
}

func (o *DeleteAPIV3CategoriesCategoryPublicIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteAPIV3CategoriesCategoryPublicIDNotFound creates a DeleteAPIV3CategoriesCategoryPublicIDNotFound with default headers values
func NewDeleteAPIV3CategoriesCategoryPublicIDNotFound() *DeleteAPIV3CategoriesCategoryPublicIDNotFound {
	return &DeleteAPIV3CategoriesCategoryPublicIDNotFound{}
}

/*DeleteAPIV3CategoriesCategoryPublicIDNotFound handles this case with default header values.

Resource does not exist
*/
type DeleteAPIV3CategoriesCategoryPublicIDNotFound struct {
}

func (o *DeleteAPIV3CategoriesCategoryPublicIDNotFound) Error() string {
	return fmt.Sprintf("[DELETE /api/v3/categories/{category-public-id}][%d] deleteApiV3CategoriesCategoryPublicIdNotFound ", 404)
}

func (o *DeleteAPIV3CategoriesCategoryPublicIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteAPIV3CategoriesCategoryPublicIDUnprocessableEntity creates a DeleteAPIV3CategoriesCategoryPublicIDUnprocessableEntity with default headers values
func NewDeleteAPIV3CategoriesCategoryPublicIDUnprocessableEntity() *DeleteAPIV3CategoriesCategoryPublicIDUnprocessableEntity {
	return &DeleteAPIV3CategoriesCategoryPublicIDUnprocessableEntity{}
}

/*DeleteAPIV3CategoriesCategoryPublicIDUnprocessableEntity handles this case with default header values.

Unprocessable
*/
type DeleteAPIV3CategoriesCategoryPublicIDUnprocessableEntity struct {
}

func (o *DeleteAPIV3CategoriesCategoryPublicIDUnprocessableEntity) Error() string {
	return fmt.Sprintf("[DELETE /api/v3/categories/{category-public-id}][%d] deleteApiV3CategoriesCategoryPublicIdUnprocessableEntity ", 422)
}

func (o *DeleteAPIV3CategoriesCategoryPublicIDUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
