// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDeleteAPIV3StoryLinksStoryLinkPublicIDParams creates a new DeleteAPIV3StoryLinksStoryLinkPublicIDParams object
// with the default values initialized.
func NewDeleteAPIV3StoryLinksStoryLinkPublicIDParams() *DeleteAPIV3StoryLinksStoryLinkPublicIDParams {
	var ()
	return &DeleteAPIV3StoryLinksStoryLinkPublicIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteAPIV3StoryLinksStoryLinkPublicIDParamsWithTimeout creates a new DeleteAPIV3StoryLinksStoryLinkPublicIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteAPIV3StoryLinksStoryLinkPublicIDParamsWithTimeout(timeout time.Duration) *DeleteAPIV3StoryLinksStoryLinkPublicIDParams {
	var ()
	return &DeleteAPIV3StoryLinksStoryLinkPublicIDParams{

		timeout: timeout,
	}
}

// NewDeleteAPIV3StoryLinksStoryLinkPublicIDParamsWithContext creates a new DeleteAPIV3StoryLinksStoryLinkPublicIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteAPIV3StoryLinksStoryLinkPublicIDParamsWithContext(ctx context.Context) *DeleteAPIV3StoryLinksStoryLinkPublicIDParams {
	var ()
	return &DeleteAPIV3StoryLinksStoryLinkPublicIDParams{

		Context: ctx,
	}
}

// NewDeleteAPIV3StoryLinksStoryLinkPublicIDParamsWithHTTPClient creates a new DeleteAPIV3StoryLinksStoryLinkPublicIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteAPIV3StoryLinksStoryLinkPublicIDParamsWithHTTPClient(client *http.Client) *DeleteAPIV3StoryLinksStoryLinkPublicIDParams {
	var ()
	return &DeleteAPIV3StoryLinksStoryLinkPublicIDParams{
		HTTPClient: client,
	}
}

/*DeleteAPIV3StoryLinksStoryLinkPublicIDParams contains all the parameters to send to the API endpoint
for the delete API v3 story links story link public ID operation typically these are written to a http.Request
*/
type DeleteAPIV3StoryLinksStoryLinkPublicIDParams struct {

	/*StoryLinkPublicID
	  The unique ID of the Story Link.

	*/
	StoryLinkPublicID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete API v3 story links story link public ID params
func (o *DeleteAPIV3StoryLinksStoryLinkPublicIDParams) WithTimeout(timeout time.Duration) *DeleteAPIV3StoryLinksStoryLinkPublicIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete API v3 story links story link public ID params
func (o *DeleteAPIV3StoryLinksStoryLinkPublicIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete API v3 story links story link public ID params
func (o *DeleteAPIV3StoryLinksStoryLinkPublicIDParams) WithContext(ctx context.Context) *DeleteAPIV3StoryLinksStoryLinkPublicIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete API v3 story links story link public ID params
func (o *DeleteAPIV3StoryLinksStoryLinkPublicIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete API v3 story links story link public ID params
func (o *DeleteAPIV3StoryLinksStoryLinkPublicIDParams) WithHTTPClient(client *http.Client) *DeleteAPIV3StoryLinksStoryLinkPublicIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete API v3 story links story link public ID params
func (o *DeleteAPIV3StoryLinksStoryLinkPublicIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithStoryLinkPublicID adds the storyLinkPublicID to the delete API v3 story links story link public ID params
func (o *DeleteAPIV3StoryLinksStoryLinkPublicIDParams) WithStoryLinkPublicID(storyLinkPublicID int64) *DeleteAPIV3StoryLinksStoryLinkPublicIDParams {
	o.SetStoryLinkPublicID(storyLinkPublicID)
	return o
}

// SetStoryLinkPublicID adds the storyLinkPublicId to the delete API v3 story links story link public ID params
func (o *DeleteAPIV3StoryLinksStoryLinkPublicIDParams) SetStoryLinkPublicID(storyLinkPublicID int64) {
	o.StoryLinkPublicID = storyLinkPublicID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteAPIV3StoryLinksStoryLinkPublicIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param story-link-public-id
	if err := r.SetPathParam("story-link-public-id", swag.FormatInt64(o.StoryLinkPublicID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
