// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteAPIV3EpicsEpicPublicIDReader is a Reader for the DeleteAPIV3EpicsEpicPublicID structure.
type DeleteAPIV3EpicsEpicPublicIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAPIV3EpicsEpicPublicIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteAPIV3EpicsEpicPublicIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteAPIV3EpicsEpicPublicIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteAPIV3EpicsEpicPublicIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewDeleteAPIV3EpicsEpicPublicIDUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteAPIV3EpicsEpicPublicIDNoContent creates a DeleteAPIV3EpicsEpicPublicIDNoContent with default headers values
func NewDeleteAPIV3EpicsEpicPublicIDNoContent() *DeleteAPIV3EpicsEpicPublicIDNoContent {
	return &DeleteAPIV3EpicsEpicPublicIDNoContent{}
}

/*DeleteAPIV3EpicsEpicPublicIDNoContent handles this case with default header values.

No Content
*/
type DeleteAPIV3EpicsEpicPublicIDNoContent struct {
}

func (o *DeleteAPIV3EpicsEpicPublicIDNoContent) Error() string {
	return fmt.Sprintf("[DELETE /api/v3/epics/{epic-public-id}][%d] deleteApiV3EpicsEpicPublicIdNoContent ", 204)
}

func (o *DeleteAPIV3EpicsEpicPublicIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteAPIV3EpicsEpicPublicIDBadRequest creates a DeleteAPIV3EpicsEpicPublicIDBadRequest with default headers values
func NewDeleteAPIV3EpicsEpicPublicIDBadRequest() *DeleteAPIV3EpicsEpicPublicIDBadRequest {
	return &DeleteAPIV3EpicsEpicPublicIDBadRequest{}
}

/*DeleteAPIV3EpicsEpicPublicIDBadRequest handles this case with default header values.

Schema mismatch
*/
type DeleteAPIV3EpicsEpicPublicIDBadRequest struct {
}

func (o *DeleteAPIV3EpicsEpicPublicIDBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /api/v3/epics/{epic-public-id}][%d] deleteApiV3EpicsEpicPublicIdBadRequest ", 400)
}

func (o *DeleteAPIV3EpicsEpicPublicIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteAPIV3EpicsEpicPublicIDNotFound creates a DeleteAPIV3EpicsEpicPublicIDNotFound with default headers values
func NewDeleteAPIV3EpicsEpicPublicIDNotFound() *DeleteAPIV3EpicsEpicPublicIDNotFound {
	return &DeleteAPIV3EpicsEpicPublicIDNotFound{}
}

/*DeleteAPIV3EpicsEpicPublicIDNotFound handles this case with default header values.

Resource does not exist
*/
type DeleteAPIV3EpicsEpicPublicIDNotFound struct {
}

func (o *DeleteAPIV3EpicsEpicPublicIDNotFound) Error() string {
	return fmt.Sprintf("[DELETE /api/v3/epics/{epic-public-id}][%d] deleteApiV3EpicsEpicPublicIdNotFound ", 404)
}

func (o *DeleteAPIV3EpicsEpicPublicIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteAPIV3EpicsEpicPublicIDUnprocessableEntity creates a DeleteAPIV3EpicsEpicPublicIDUnprocessableEntity with default headers values
func NewDeleteAPIV3EpicsEpicPublicIDUnprocessableEntity() *DeleteAPIV3EpicsEpicPublicIDUnprocessableEntity {
	return &DeleteAPIV3EpicsEpicPublicIDUnprocessableEntity{}
}

/*DeleteAPIV3EpicsEpicPublicIDUnprocessableEntity handles this case with default header values.

Unprocessable
*/
type DeleteAPIV3EpicsEpicPublicIDUnprocessableEntity struct {
}

func (o *DeleteAPIV3EpicsEpicPublicIDUnprocessableEntity) Error() string {
	return fmt.Sprintf("[DELETE /api/v3/epics/{epic-public-id}][%d] deleteApiV3EpicsEpicPublicIdUnprocessableEntity ", 422)
}

func (o *DeleteAPIV3EpicsEpicPublicIDUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
