// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDeleteAPIV3StoriesStoryPublicIDTasksTaskPublicIDParams creates a new DeleteAPIV3StoriesStoryPublicIDTasksTaskPublicIDParams object
// with the default values initialized.
func NewDeleteAPIV3StoriesStoryPublicIDTasksTaskPublicIDParams() *DeleteAPIV3StoriesStoryPublicIDTasksTaskPublicIDParams {
	var ()
	return &DeleteAPIV3StoriesStoryPublicIDTasksTaskPublicIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteAPIV3StoriesStoryPublicIDTasksTaskPublicIDParamsWithTimeout creates a new DeleteAPIV3StoriesStoryPublicIDTasksTaskPublicIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteAPIV3StoriesStoryPublicIDTasksTaskPublicIDParamsWithTimeout(timeout time.Duration) *DeleteAPIV3StoriesStoryPublicIDTasksTaskPublicIDParams {
	var ()
	return &DeleteAPIV3StoriesStoryPublicIDTasksTaskPublicIDParams{

		timeout: timeout,
	}
}

// NewDeleteAPIV3StoriesStoryPublicIDTasksTaskPublicIDParamsWithContext creates a new DeleteAPIV3StoriesStoryPublicIDTasksTaskPublicIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteAPIV3StoriesStoryPublicIDTasksTaskPublicIDParamsWithContext(ctx context.Context) *DeleteAPIV3StoriesStoryPublicIDTasksTaskPublicIDParams {
	var ()
	return &DeleteAPIV3StoriesStoryPublicIDTasksTaskPublicIDParams{

		Context: ctx,
	}
}

// NewDeleteAPIV3StoriesStoryPublicIDTasksTaskPublicIDParamsWithHTTPClient creates a new DeleteAPIV3StoriesStoryPublicIDTasksTaskPublicIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteAPIV3StoriesStoryPublicIDTasksTaskPublicIDParamsWithHTTPClient(client *http.Client) *DeleteAPIV3StoriesStoryPublicIDTasksTaskPublicIDParams {
	var ()
	return &DeleteAPIV3StoriesStoryPublicIDTasksTaskPublicIDParams{
		HTTPClient: client,
	}
}

/*DeleteAPIV3StoriesStoryPublicIDTasksTaskPublicIDParams contains all the parameters to send to the API endpoint
for the delete API v3 stories story public ID tasks task public ID operation typically these are written to a http.Request
*/
type DeleteAPIV3StoriesStoryPublicIDTasksTaskPublicIDParams struct {

	/*StoryPublicID
	  The unique ID of the Story this Task is associated with.

	*/
	StoryPublicID int64
	/*TaskPublicID
	  The unique ID of the Task.

	*/
	TaskPublicID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete API v3 stories story public ID tasks task public ID params
func (o *DeleteAPIV3StoriesStoryPublicIDTasksTaskPublicIDParams) WithTimeout(timeout time.Duration) *DeleteAPIV3StoriesStoryPublicIDTasksTaskPublicIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete API v3 stories story public ID tasks task public ID params
func (o *DeleteAPIV3StoriesStoryPublicIDTasksTaskPublicIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete API v3 stories story public ID tasks task public ID params
func (o *DeleteAPIV3StoriesStoryPublicIDTasksTaskPublicIDParams) WithContext(ctx context.Context) *DeleteAPIV3StoriesStoryPublicIDTasksTaskPublicIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete API v3 stories story public ID tasks task public ID params
func (o *DeleteAPIV3StoriesStoryPublicIDTasksTaskPublicIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete API v3 stories story public ID tasks task public ID params
func (o *DeleteAPIV3StoriesStoryPublicIDTasksTaskPublicIDParams) WithHTTPClient(client *http.Client) *DeleteAPIV3StoriesStoryPublicIDTasksTaskPublicIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete API v3 stories story public ID tasks task public ID params
func (o *DeleteAPIV3StoriesStoryPublicIDTasksTaskPublicIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithStoryPublicID adds the storyPublicID to the delete API v3 stories story public ID tasks task public ID params
func (o *DeleteAPIV3StoriesStoryPublicIDTasksTaskPublicIDParams) WithStoryPublicID(storyPublicID int64) *DeleteAPIV3StoriesStoryPublicIDTasksTaskPublicIDParams {
	o.SetStoryPublicID(storyPublicID)
	return o
}

// SetStoryPublicID adds the storyPublicId to the delete API v3 stories story public ID tasks task public ID params
func (o *DeleteAPIV3StoriesStoryPublicIDTasksTaskPublicIDParams) SetStoryPublicID(storyPublicID int64) {
	o.StoryPublicID = storyPublicID
}

// WithTaskPublicID adds the taskPublicID to the delete API v3 stories story public ID tasks task public ID params
func (o *DeleteAPIV3StoriesStoryPublicIDTasksTaskPublicIDParams) WithTaskPublicID(taskPublicID int64) *DeleteAPIV3StoriesStoryPublicIDTasksTaskPublicIDParams {
	o.SetTaskPublicID(taskPublicID)
	return o
}

// SetTaskPublicID adds the taskPublicId to the delete API v3 stories story public ID tasks task public ID params
func (o *DeleteAPIV3StoriesStoryPublicIDTasksTaskPublicIDParams) SetTaskPublicID(taskPublicID int64) {
	o.TaskPublicID = taskPublicID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteAPIV3StoriesStoryPublicIDTasksTaskPublicIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param story-public-id
	if err := r.SetPathParam("story-public-id", swag.FormatInt64(o.StoryPublicID)); err != nil {
		return err
	}

	// path param task-public-id
	if err := r.SetPathParam("task-public-id", swag.FormatInt64(o.TaskPublicID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
