// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/bateau-eng/chapi/v0/pkg/models"
)

// NewDeleteAPIV3StoriesBulkParams creates a new DeleteAPIV3StoriesBulkParams object
// with the default values initialized.
func NewDeleteAPIV3StoriesBulkParams() *DeleteAPIV3StoriesBulkParams {
	var ()
	return &DeleteAPIV3StoriesBulkParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteAPIV3StoriesBulkParamsWithTimeout creates a new DeleteAPIV3StoriesBulkParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteAPIV3StoriesBulkParamsWithTimeout(timeout time.Duration) *DeleteAPIV3StoriesBulkParams {
	var ()
	return &DeleteAPIV3StoriesBulkParams{

		timeout: timeout,
	}
}

// NewDeleteAPIV3StoriesBulkParamsWithContext creates a new DeleteAPIV3StoriesBulkParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteAPIV3StoriesBulkParamsWithContext(ctx context.Context) *DeleteAPIV3StoriesBulkParams {
	var ()
	return &DeleteAPIV3StoriesBulkParams{

		Context: ctx,
	}
}

// NewDeleteAPIV3StoriesBulkParamsWithHTTPClient creates a new DeleteAPIV3StoriesBulkParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteAPIV3StoriesBulkParamsWithHTTPClient(client *http.Client) *DeleteAPIV3StoriesBulkParams {
	var ()
	return &DeleteAPIV3StoriesBulkParams{
		HTTPClient: client,
	}
}

/*DeleteAPIV3StoriesBulkParams contains all the parameters to send to the API endpoint
for the delete API v3 stories bulk operation typically these are written to a http.Request
*/
type DeleteAPIV3StoriesBulkParams struct {

	/*DeleteStories*/
	DeleteStories *models.DeleteStories

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete API v3 stories bulk params
func (o *DeleteAPIV3StoriesBulkParams) WithTimeout(timeout time.Duration) *DeleteAPIV3StoriesBulkParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete API v3 stories bulk params
func (o *DeleteAPIV3StoriesBulkParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete API v3 stories bulk params
func (o *DeleteAPIV3StoriesBulkParams) WithContext(ctx context.Context) *DeleteAPIV3StoriesBulkParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete API v3 stories bulk params
func (o *DeleteAPIV3StoriesBulkParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete API v3 stories bulk params
func (o *DeleteAPIV3StoriesBulkParams) WithHTTPClient(client *http.Client) *DeleteAPIV3StoriesBulkParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete API v3 stories bulk params
func (o *DeleteAPIV3StoriesBulkParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDeleteStories adds the deleteStories to the delete API v3 stories bulk params
func (o *DeleteAPIV3StoriesBulkParams) WithDeleteStories(deleteStories *models.DeleteStories) *DeleteAPIV3StoriesBulkParams {
	o.SetDeleteStories(deleteStories)
	return o
}

// SetDeleteStories adds the deleteStories to the delete API v3 stories bulk params
func (o *DeleteAPIV3StoriesBulkParams) SetDeleteStories(deleteStories *models.DeleteStories) {
	o.DeleteStories = deleteStories
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteAPIV3StoriesBulkParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.DeleteStories != nil {
		if err := r.SetBodyParam(o.DeleteStories); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
