// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteAPIV3EpicsEpicPublicIDCommentsCommentPublicIDReader is a Reader for the DeleteAPIV3EpicsEpicPublicIDCommentsCommentPublicID structure.
type DeleteAPIV3EpicsEpicPublicIDCommentsCommentPublicIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAPIV3EpicsEpicPublicIDCommentsCommentPublicIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteAPIV3EpicsEpicPublicIDCommentsCommentPublicIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteAPIV3EpicsEpicPublicIDCommentsCommentPublicIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteAPIV3EpicsEpicPublicIDCommentsCommentPublicIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewDeleteAPIV3EpicsEpicPublicIDCommentsCommentPublicIDUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteAPIV3EpicsEpicPublicIDCommentsCommentPublicIDNoContent creates a DeleteAPIV3EpicsEpicPublicIDCommentsCommentPublicIDNoContent with default headers values
func NewDeleteAPIV3EpicsEpicPublicIDCommentsCommentPublicIDNoContent() *DeleteAPIV3EpicsEpicPublicIDCommentsCommentPublicIDNoContent {
	return &DeleteAPIV3EpicsEpicPublicIDCommentsCommentPublicIDNoContent{}
}

/*DeleteAPIV3EpicsEpicPublicIDCommentsCommentPublicIDNoContent handles this case with default header values.

No Content
*/
type DeleteAPIV3EpicsEpicPublicIDCommentsCommentPublicIDNoContent struct {
}

func (o *DeleteAPIV3EpicsEpicPublicIDCommentsCommentPublicIDNoContent) Error() string {
	return fmt.Sprintf("[DELETE /api/v3/epics/{epic-public-id}/comments/{comment-public-id}][%d] deleteApiV3EpicsEpicPublicIdCommentsCommentPublicIdNoContent ", 204)
}

func (o *DeleteAPIV3EpicsEpicPublicIDCommentsCommentPublicIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteAPIV3EpicsEpicPublicIDCommentsCommentPublicIDBadRequest creates a DeleteAPIV3EpicsEpicPublicIDCommentsCommentPublicIDBadRequest with default headers values
func NewDeleteAPIV3EpicsEpicPublicIDCommentsCommentPublicIDBadRequest() *DeleteAPIV3EpicsEpicPublicIDCommentsCommentPublicIDBadRequest {
	return &DeleteAPIV3EpicsEpicPublicIDCommentsCommentPublicIDBadRequest{}
}

/*DeleteAPIV3EpicsEpicPublicIDCommentsCommentPublicIDBadRequest handles this case with default header values.

Schema mismatch
*/
type DeleteAPIV3EpicsEpicPublicIDCommentsCommentPublicIDBadRequest struct {
}

func (o *DeleteAPIV3EpicsEpicPublicIDCommentsCommentPublicIDBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /api/v3/epics/{epic-public-id}/comments/{comment-public-id}][%d] deleteApiV3EpicsEpicPublicIdCommentsCommentPublicIdBadRequest ", 400)
}

func (o *DeleteAPIV3EpicsEpicPublicIDCommentsCommentPublicIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteAPIV3EpicsEpicPublicIDCommentsCommentPublicIDNotFound creates a DeleteAPIV3EpicsEpicPublicIDCommentsCommentPublicIDNotFound with default headers values
func NewDeleteAPIV3EpicsEpicPublicIDCommentsCommentPublicIDNotFound() *DeleteAPIV3EpicsEpicPublicIDCommentsCommentPublicIDNotFound {
	return &DeleteAPIV3EpicsEpicPublicIDCommentsCommentPublicIDNotFound{}
}

/*DeleteAPIV3EpicsEpicPublicIDCommentsCommentPublicIDNotFound handles this case with default header values.

Resource does not exist
*/
type DeleteAPIV3EpicsEpicPublicIDCommentsCommentPublicIDNotFound struct {
}

func (o *DeleteAPIV3EpicsEpicPublicIDCommentsCommentPublicIDNotFound) Error() string {
	return fmt.Sprintf("[DELETE /api/v3/epics/{epic-public-id}/comments/{comment-public-id}][%d] deleteApiV3EpicsEpicPublicIdCommentsCommentPublicIdNotFound ", 404)
}

func (o *DeleteAPIV3EpicsEpicPublicIDCommentsCommentPublicIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteAPIV3EpicsEpicPublicIDCommentsCommentPublicIDUnprocessableEntity creates a DeleteAPIV3EpicsEpicPublicIDCommentsCommentPublicIDUnprocessableEntity with default headers values
func NewDeleteAPIV3EpicsEpicPublicIDCommentsCommentPublicIDUnprocessableEntity() *DeleteAPIV3EpicsEpicPublicIDCommentsCommentPublicIDUnprocessableEntity {
	return &DeleteAPIV3EpicsEpicPublicIDCommentsCommentPublicIDUnprocessableEntity{}
}

/*DeleteAPIV3EpicsEpicPublicIDCommentsCommentPublicIDUnprocessableEntity handles this case with default header values.

Unprocessable
*/
type DeleteAPIV3EpicsEpicPublicIDCommentsCommentPublicIDUnprocessableEntity struct {
}

func (o *DeleteAPIV3EpicsEpicPublicIDCommentsCommentPublicIDUnprocessableEntity) Error() string {
	return fmt.Sprintf("[DELETE /api/v3/epics/{epic-public-id}/comments/{comment-public-id}][%d] deleteApiV3EpicsEpicPublicIdCommentsCommentPublicIdUnprocessableEntity ", 422)
}

func (o *DeleteAPIV3EpicsEpicPublicIDCommentsCommentPublicIDUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
