// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAPIV3MemberParams creates a new GetAPIV3MemberParams object
// with the default values initialized.
func NewGetAPIV3MemberParams() *GetAPIV3MemberParams {

	return &GetAPIV3MemberParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIV3MemberParamsWithTimeout creates a new GetAPIV3MemberParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAPIV3MemberParamsWithTimeout(timeout time.Duration) *GetAPIV3MemberParams {

	return &GetAPIV3MemberParams{

		timeout: timeout,
	}
}

// NewGetAPIV3MemberParamsWithContext creates a new GetAPIV3MemberParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAPIV3MemberParamsWithContext(ctx context.Context) *GetAPIV3MemberParams {

	return &GetAPIV3MemberParams{

		Context: ctx,
	}
}

// NewGetAPIV3MemberParamsWithHTTPClient creates a new GetAPIV3MemberParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAPIV3MemberParamsWithHTTPClient(client *http.Client) *GetAPIV3MemberParams {

	return &GetAPIV3MemberParams{
		HTTPClient: client,
	}
}

/*GetAPIV3MemberParams contains all the parameters to send to the API endpoint
for the get API v3 member operation typically these are written to a http.Request
*/
type GetAPIV3MemberParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get API v3 member params
func (o *GetAPIV3MemberParams) WithTimeout(timeout time.Duration) *GetAPIV3MemberParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API v3 member params
func (o *GetAPIV3MemberParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API v3 member params
func (o *GetAPIV3MemberParams) WithContext(ctx context.Context) *GetAPIV3MemberParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API v3 member params
func (o *GetAPIV3MemberParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API v3 member params
func (o *GetAPIV3MemberParams) WithHTTPClient(client *http.Client) *GetAPIV3MemberParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API v3 member params
func (o *GetAPIV3MemberParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIV3MemberParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
