// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/bateau-eng/chapi/v0/pkg/models"
)

// GetAPIV3ProjectsReader is a Reader for the GetAPIV3Projects structure.
type GetAPIV3ProjectsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV3ProjectsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIV3ProjectsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetAPIV3ProjectsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetAPIV3ProjectsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewGetAPIV3ProjectsUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAPIV3ProjectsOK creates a GetAPIV3ProjectsOK with default headers values
func NewGetAPIV3ProjectsOK() *GetAPIV3ProjectsOK {
	return &GetAPIV3ProjectsOK{}
}

/*GetAPIV3ProjectsOK handles this case with default header values.

Resource
*/
type GetAPIV3ProjectsOK struct {
	Payload []*models.Project
}

func (o *GetAPIV3ProjectsOK) Error() string {
	return fmt.Sprintf("[GET /api/v3/projects][%d] getApiV3ProjectsOK  %+v", 200, o.Payload)
}

func (o *GetAPIV3ProjectsOK) GetPayload() []*models.Project {
	return o.Payload
}

func (o *GetAPIV3ProjectsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIV3ProjectsBadRequest creates a GetAPIV3ProjectsBadRequest with default headers values
func NewGetAPIV3ProjectsBadRequest() *GetAPIV3ProjectsBadRequest {
	return &GetAPIV3ProjectsBadRequest{}
}

/*GetAPIV3ProjectsBadRequest handles this case with default header values.

Schema mismatch
*/
type GetAPIV3ProjectsBadRequest struct {
}

func (o *GetAPIV3ProjectsBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/v3/projects][%d] getApiV3ProjectsBadRequest ", 400)
}

func (o *GetAPIV3ProjectsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAPIV3ProjectsNotFound creates a GetAPIV3ProjectsNotFound with default headers values
func NewGetAPIV3ProjectsNotFound() *GetAPIV3ProjectsNotFound {
	return &GetAPIV3ProjectsNotFound{}
}

/*GetAPIV3ProjectsNotFound handles this case with default header values.

Resource does not exist
*/
type GetAPIV3ProjectsNotFound struct {
}

func (o *GetAPIV3ProjectsNotFound) Error() string {
	return fmt.Sprintf("[GET /api/v3/projects][%d] getApiV3ProjectsNotFound ", 404)
}

func (o *GetAPIV3ProjectsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAPIV3ProjectsUnprocessableEntity creates a GetAPIV3ProjectsUnprocessableEntity with default headers values
func NewGetAPIV3ProjectsUnprocessableEntity() *GetAPIV3ProjectsUnprocessableEntity {
	return &GetAPIV3ProjectsUnprocessableEntity{}
}

/*GetAPIV3ProjectsUnprocessableEntity handles this case with default header values.

Unprocessable
*/
type GetAPIV3ProjectsUnprocessableEntity struct {
}

func (o *GetAPIV3ProjectsUnprocessableEntity) Error() string {
	return fmt.Sprintf("[GET /api/v3/projects][%d] getApiV3ProjectsUnprocessableEntity ", 422)
}

func (o *GetAPIV3ProjectsUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
