// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/bateau-eng/chapi/v0/pkg/models"
)

// GetAPIV3GroupsGroupPublicIDReader is a Reader for the GetAPIV3GroupsGroupPublicID structure.
type GetAPIV3GroupsGroupPublicIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV3GroupsGroupPublicIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIV3GroupsGroupPublicIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetAPIV3GroupsGroupPublicIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetAPIV3GroupsGroupPublicIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewGetAPIV3GroupsGroupPublicIDUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAPIV3GroupsGroupPublicIDOK creates a GetAPIV3GroupsGroupPublicIDOK with default headers values
func NewGetAPIV3GroupsGroupPublicIDOK() *GetAPIV3GroupsGroupPublicIDOK {
	return &GetAPIV3GroupsGroupPublicIDOK{}
}

/*GetAPIV3GroupsGroupPublicIDOK handles this case with default header values.

Resource
*/
type GetAPIV3GroupsGroupPublicIDOK struct {
	Payload *models.Group
}

func (o *GetAPIV3GroupsGroupPublicIDOK) Error() string {
	return fmt.Sprintf("[GET /api/v3/groups/{group-public-id}][%d] getApiV3GroupsGroupPublicIdOK  %+v", 200, o.Payload)
}

func (o *GetAPIV3GroupsGroupPublicIDOK) GetPayload() *models.Group {
	return o.Payload
}

func (o *GetAPIV3GroupsGroupPublicIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Group)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIV3GroupsGroupPublicIDBadRequest creates a GetAPIV3GroupsGroupPublicIDBadRequest with default headers values
func NewGetAPIV3GroupsGroupPublicIDBadRequest() *GetAPIV3GroupsGroupPublicIDBadRequest {
	return &GetAPIV3GroupsGroupPublicIDBadRequest{}
}

/*GetAPIV3GroupsGroupPublicIDBadRequest handles this case with default header values.

Schema mismatch
*/
type GetAPIV3GroupsGroupPublicIDBadRequest struct {
}

func (o *GetAPIV3GroupsGroupPublicIDBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/v3/groups/{group-public-id}][%d] getApiV3GroupsGroupPublicIdBadRequest ", 400)
}

func (o *GetAPIV3GroupsGroupPublicIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAPIV3GroupsGroupPublicIDNotFound creates a GetAPIV3GroupsGroupPublicIDNotFound with default headers values
func NewGetAPIV3GroupsGroupPublicIDNotFound() *GetAPIV3GroupsGroupPublicIDNotFound {
	return &GetAPIV3GroupsGroupPublicIDNotFound{}
}

/*GetAPIV3GroupsGroupPublicIDNotFound handles this case with default header values.

Resource does not exist
*/
type GetAPIV3GroupsGroupPublicIDNotFound struct {
}

func (o *GetAPIV3GroupsGroupPublicIDNotFound) Error() string {
	return fmt.Sprintf("[GET /api/v3/groups/{group-public-id}][%d] getApiV3GroupsGroupPublicIdNotFound ", 404)
}

func (o *GetAPIV3GroupsGroupPublicIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAPIV3GroupsGroupPublicIDUnprocessableEntity creates a GetAPIV3GroupsGroupPublicIDUnprocessableEntity with default headers values
func NewGetAPIV3GroupsGroupPublicIDUnprocessableEntity() *GetAPIV3GroupsGroupPublicIDUnprocessableEntity {
	return &GetAPIV3GroupsGroupPublicIDUnprocessableEntity{}
}

/*GetAPIV3GroupsGroupPublicIDUnprocessableEntity handles this case with default header values.

Unprocessable
*/
type GetAPIV3GroupsGroupPublicIDUnprocessableEntity struct {
}

func (o *GetAPIV3GroupsGroupPublicIDUnprocessableEntity) Error() string {
	return fmt.Sprintf("[GET /api/v3/groups/{group-public-id}][%d] getApiV3GroupsGroupPublicIdUnprocessableEntity ", 422)
}

func (o *GetAPIV3GroupsGroupPublicIDUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
