// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/bateau-eng/chapi/pkg/models"
)

// GetAPIV3MilestonesMilestonePublicIDEpicsReader is a Reader for the GetAPIV3MilestonesMilestonePublicIDEpics structure.
type GetAPIV3MilestonesMilestonePublicIDEpicsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV3MilestonesMilestonePublicIDEpicsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIV3MilestonesMilestonePublicIDEpicsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetAPIV3MilestonesMilestonePublicIDEpicsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetAPIV3MilestonesMilestonePublicIDEpicsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewGetAPIV3MilestonesMilestonePublicIDEpicsUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAPIV3MilestonesMilestonePublicIDEpicsOK creates a GetAPIV3MilestonesMilestonePublicIDEpicsOK with default headers values
func NewGetAPIV3MilestonesMilestonePublicIDEpicsOK() *GetAPIV3MilestonesMilestonePublicIDEpicsOK {
	return &GetAPIV3MilestonesMilestonePublicIDEpicsOK{}
}

/*GetAPIV3MilestonesMilestonePublicIDEpicsOK handles this case with default header values.

Resource
*/
type GetAPIV3MilestonesMilestonePublicIDEpicsOK struct {
	Payload []*models.EpicSlim
}

func (o *GetAPIV3MilestonesMilestonePublicIDEpicsOK) Error() string {
	return fmt.Sprintf("[GET /api/v3/milestones/{milestone-public-id}/epics][%d] getApiV3MilestonesMilestonePublicIdEpicsOK  %+v", 200, o.Payload)
}

func (o *GetAPIV3MilestonesMilestonePublicIDEpicsOK) GetPayload() []*models.EpicSlim {
	return o.Payload
}

func (o *GetAPIV3MilestonesMilestonePublicIDEpicsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIV3MilestonesMilestonePublicIDEpicsBadRequest creates a GetAPIV3MilestonesMilestonePublicIDEpicsBadRequest with default headers values
func NewGetAPIV3MilestonesMilestonePublicIDEpicsBadRequest() *GetAPIV3MilestonesMilestonePublicIDEpicsBadRequest {
	return &GetAPIV3MilestonesMilestonePublicIDEpicsBadRequest{}
}

/*GetAPIV3MilestonesMilestonePublicIDEpicsBadRequest handles this case with default header values.

Schema mismatch
*/
type GetAPIV3MilestonesMilestonePublicIDEpicsBadRequest struct {
}

func (o *GetAPIV3MilestonesMilestonePublicIDEpicsBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/v3/milestones/{milestone-public-id}/epics][%d] getApiV3MilestonesMilestonePublicIdEpicsBadRequest ", 400)
}

func (o *GetAPIV3MilestonesMilestonePublicIDEpicsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAPIV3MilestonesMilestonePublicIDEpicsNotFound creates a GetAPIV3MilestonesMilestonePublicIDEpicsNotFound with default headers values
func NewGetAPIV3MilestonesMilestonePublicIDEpicsNotFound() *GetAPIV3MilestonesMilestonePublicIDEpicsNotFound {
	return &GetAPIV3MilestonesMilestonePublicIDEpicsNotFound{}
}

/*GetAPIV3MilestonesMilestonePublicIDEpicsNotFound handles this case with default header values.

Resource does not exist
*/
type GetAPIV3MilestonesMilestonePublicIDEpicsNotFound struct {
}

func (o *GetAPIV3MilestonesMilestonePublicIDEpicsNotFound) Error() string {
	return fmt.Sprintf("[GET /api/v3/milestones/{milestone-public-id}/epics][%d] getApiV3MilestonesMilestonePublicIdEpicsNotFound ", 404)
}

func (o *GetAPIV3MilestonesMilestonePublicIDEpicsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAPIV3MilestonesMilestonePublicIDEpicsUnprocessableEntity creates a GetAPIV3MilestonesMilestonePublicIDEpicsUnprocessableEntity with default headers values
func NewGetAPIV3MilestonesMilestonePublicIDEpicsUnprocessableEntity() *GetAPIV3MilestonesMilestonePublicIDEpicsUnprocessableEntity {
	return &GetAPIV3MilestonesMilestonePublicIDEpicsUnprocessableEntity{}
}

/*GetAPIV3MilestonesMilestonePublicIDEpicsUnprocessableEntity handles this case with default header values.

Unprocessable
*/
type GetAPIV3MilestonesMilestonePublicIDEpicsUnprocessableEntity struct {
}

func (o *GetAPIV3MilestonesMilestonePublicIDEpicsUnprocessableEntity) Error() string {
	return fmt.Sprintf("[GET /api/v3/milestones/{milestone-public-id}/epics][%d] getApiV3MilestonesMilestonePublicIdEpicsUnprocessableEntity ", 422)
}

func (o *GetAPIV3MilestonesMilestonePublicIDEpicsUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
