// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/bateau-eng/chapi/v0/pkg/models"
)

// GetAPIV3ProjectsProjectPublicIDReader is a Reader for the GetAPIV3ProjectsProjectPublicID structure.
type GetAPIV3ProjectsProjectPublicIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV3ProjectsProjectPublicIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIV3ProjectsProjectPublicIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetAPIV3ProjectsProjectPublicIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetAPIV3ProjectsProjectPublicIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewGetAPIV3ProjectsProjectPublicIDUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAPIV3ProjectsProjectPublicIDOK creates a GetAPIV3ProjectsProjectPublicIDOK with default headers values
func NewGetAPIV3ProjectsProjectPublicIDOK() *GetAPIV3ProjectsProjectPublicIDOK {
	return &GetAPIV3ProjectsProjectPublicIDOK{}
}

/*GetAPIV3ProjectsProjectPublicIDOK handles this case with default header values.

Resource
*/
type GetAPIV3ProjectsProjectPublicIDOK struct {
	Payload *models.Project
}

func (o *GetAPIV3ProjectsProjectPublicIDOK) Error() string {
	return fmt.Sprintf("[GET /api/v3/projects/{project-public-id}][%d] getApiV3ProjectsProjectPublicIdOK  %+v", 200, o.Payload)
}

func (o *GetAPIV3ProjectsProjectPublicIDOK) GetPayload() *models.Project {
	return o.Payload
}

func (o *GetAPIV3ProjectsProjectPublicIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Project)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIV3ProjectsProjectPublicIDBadRequest creates a GetAPIV3ProjectsProjectPublicIDBadRequest with default headers values
func NewGetAPIV3ProjectsProjectPublicIDBadRequest() *GetAPIV3ProjectsProjectPublicIDBadRequest {
	return &GetAPIV3ProjectsProjectPublicIDBadRequest{}
}

/*GetAPIV3ProjectsProjectPublicIDBadRequest handles this case with default header values.

Schema mismatch
*/
type GetAPIV3ProjectsProjectPublicIDBadRequest struct {
}

func (o *GetAPIV3ProjectsProjectPublicIDBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/v3/projects/{project-public-id}][%d] getApiV3ProjectsProjectPublicIdBadRequest ", 400)
}

func (o *GetAPIV3ProjectsProjectPublicIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAPIV3ProjectsProjectPublicIDNotFound creates a GetAPIV3ProjectsProjectPublicIDNotFound with default headers values
func NewGetAPIV3ProjectsProjectPublicIDNotFound() *GetAPIV3ProjectsProjectPublicIDNotFound {
	return &GetAPIV3ProjectsProjectPublicIDNotFound{}
}

/*GetAPIV3ProjectsProjectPublicIDNotFound handles this case with default header values.

Resource does not exist
*/
type GetAPIV3ProjectsProjectPublicIDNotFound struct {
}

func (o *GetAPIV3ProjectsProjectPublicIDNotFound) Error() string {
	return fmt.Sprintf("[GET /api/v3/projects/{project-public-id}][%d] getApiV3ProjectsProjectPublicIdNotFound ", 404)
}

func (o *GetAPIV3ProjectsProjectPublicIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAPIV3ProjectsProjectPublicIDUnprocessableEntity creates a GetAPIV3ProjectsProjectPublicIDUnprocessableEntity with default headers values
func NewGetAPIV3ProjectsProjectPublicIDUnprocessableEntity() *GetAPIV3ProjectsProjectPublicIDUnprocessableEntity {
	return &GetAPIV3ProjectsProjectPublicIDUnprocessableEntity{}
}

/*GetAPIV3ProjectsProjectPublicIDUnprocessableEntity handles this case with default header values.

Unprocessable
*/
type GetAPIV3ProjectsProjectPublicIDUnprocessableEntity struct {
}

func (o *GetAPIV3ProjectsProjectPublicIDUnprocessableEntity) Error() string {
	return fmt.Sprintf("[GET /api/v3/projects/{project-public-id}][%d] getApiV3ProjectsProjectPublicIdUnprocessableEntity ", 422)
}

func (o *GetAPIV3ProjectsProjectPublicIDUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
