// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAPIV3EntityTemplatesEntityTemplatePublicIDParams creates a new GetAPIV3EntityTemplatesEntityTemplatePublicIDParams object
// with the default values initialized.
func NewGetAPIV3EntityTemplatesEntityTemplatePublicIDParams() *GetAPIV3EntityTemplatesEntityTemplatePublicIDParams {
	var ()
	return &GetAPIV3EntityTemplatesEntityTemplatePublicIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIV3EntityTemplatesEntityTemplatePublicIDParamsWithTimeout creates a new GetAPIV3EntityTemplatesEntityTemplatePublicIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAPIV3EntityTemplatesEntityTemplatePublicIDParamsWithTimeout(timeout time.Duration) *GetAPIV3EntityTemplatesEntityTemplatePublicIDParams {
	var ()
	return &GetAPIV3EntityTemplatesEntityTemplatePublicIDParams{

		timeout: timeout,
	}
}

// NewGetAPIV3EntityTemplatesEntityTemplatePublicIDParamsWithContext creates a new GetAPIV3EntityTemplatesEntityTemplatePublicIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAPIV3EntityTemplatesEntityTemplatePublicIDParamsWithContext(ctx context.Context) *GetAPIV3EntityTemplatesEntityTemplatePublicIDParams {
	var ()
	return &GetAPIV3EntityTemplatesEntityTemplatePublicIDParams{

		Context: ctx,
	}
}

// NewGetAPIV3EntityTemplatesEntityTemplatePublicIDParamsWithHTTPClient creates a new GetAPIV3EntityTemplatesEntityTemplatePublicIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAPIV3EntityTemplatesEntityTemplatePublicIDParamsWithHTTPClient(client *http.Client) *GetAPIV3EntityTemplatesEntityTemplatePublicIDParams {
	var ()
	return &GetAPIV3EntityTemplatesEntityTemplatePublicIDParams{
		HTTPClient: client,
	}
}

/*GetAPIV3EntityTemplatesEntityTemplatePublicIDParams contains all the parameters to send to the API endpoint
for the get API v3 entity templates entity template public ID operation typically these are written to a http.Request
*/
type GetAPIV3EntityTemplatesEntityTemplatePublicIDParams struct {

	/*EntityTemplatePublicID
	  The unique ID of the entity template.

	*/
	EntityTemplatePublicID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get API v3 entity templates entity template public ID params
func (o *GetAPIV3EntityTemplatesEntityTemplatePublicIDParams) WithTimeout(timeout time.Duration) *GetAPIV3EntityTemplatesEntityTemplatePublicIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API v3 entity templates entity template public ID params
func (o *GetAPIV3EntityTemplatesEntityTemplatePublicIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API v3 entity templates entity template public ID params
func (o *GetAPIV3EntityTemplatesEntityTemplatePublicIDParams) WithContext(ctx context.Context) *GetAPIV3EntityTemplatesEntityTemplatePublicIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API v3 entity templates entity template public ID params
func (o *GetAPIV3EntityTemplatesEntityTemplatePublicIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API v3 entity templates entity template public ID params
func (o *GetAPIV3EntityTemplatesEntityTemplatePublicIDParams) WithHTTPClient(client *http.Client) *GetAPIV3EntityTemplatesEntityTemplatePublicIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API v3 entity templates entity template public ID params
func (o *GetAPIV3EntityTemplatesEntityTemplatePublicIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEntityTemplatePublicID adds the entityTemplatePublicID to the get API v3 entity templates entity template public ID params
func (o *GetAPIV3EntityTemplatesEntityTemplatePublicIDParams) WithEntityTemplatePublicID(entityTemplatePublicID strfmt.UUID) *GetAPIV3EntityTemplatesEntityTemplatePublicIDParams {
	o.SetEntityTemplatePublicID(entityTemplatePublicID)
	return o
}

// SetEntityTemplatePublicID adds the entityTemplatePublicId to the get API v3 entity templates entity template public ID params
func (o *GetAPIV3EntityTemplatesEntityTemplatePublicIDParams) SetEntityTemplatePublicID(entityTemplatePublicID strfmt.UUID) {
	o.EntityTemplatePublicID = entityTemplatePublicID
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIV3EntityTemplatesEntityTemplatePublicIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param entity-template-public-id
	if err := r.SetPathParam("entity-template-public-id", o.EntityTemplatePublicID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
