// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetAPIV3RepositoriesRepoPublicIDParams creates a new GetAPIV3RepositoriesRepoPublicIDParams object
// with the default values initialized.
func NewGetAPIV3RepositoriesRepoPublicIDParams() *GetAPIV3RepositoriesRepoPublicIDParams {
	var ()
	return &GetAPIV3RepositoriesRepoPublicIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIV3RepositoriesRepoPublicIDParamsWithTimeout creates a new GetAPIV3RepositoriesRepoPublicIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAPIV3RepositoriesRepoPublicIDParamsWithTimeout(timeout time.Duration) *GetAPIV3RepositoriesRepoPublicIDParams {
	var ()
	return &GetAPIV3RepositoriesRepoPublicIDParams{

		timeout: timeout,
	}
}

// NewGetAPIV3RepositoriesRepoPublicIDParamsWithContext creates a new GetAPIV3RepositoriesRepoPublicIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAPIV3RepositoriesRepoPublicIDParamsWithContext(ctx context.Context) *GetAPIV3RepositoriesRepoPublicIDParams {
	var ()
	return &GetAPIV3RepositoriesRepoPublicIDParams{

		Context: ctx,
	}
}

// NewGetAPIV3RepositoriesRepoPublicIDParamsWithHTTPClient creates a new GetAPIV3RepositoriesRepoPublicIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAPIV3RepositoriesRepoPublicIDParamsWithHTTPClient(client *http.Client) *GetAPIV3RepositoriesRepoPublicIDParams {
	var ()
	return &GetAPIV3RepositoriesRepoPublicIDParams{
		HTTPClient: client,
	}
}

/*GetAPIV3RepositoriesRepoPublicIDParams contains all the parameters to send to the API endpoint
for the get API v3 repositories repo public ID operation typically these are written to a http.Request
*/
type GetAPIV3RepositoriesRepoPublicIDParams struct {

	/*RepoPublicID
	  The unique ID of the Repository.

	*/
	RepoPublicID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get API v3 repositories repo public ID params
func (o *GetAPIV3RepositoriesRepoPublicIDParams) WithTimeout(timeout time.Duration) *GetAPIV3RepositoriesRepoPublicIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API v3 repositories repo public ID params
func (o *GetAPIV3RepositoriesRepoPublicIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API v3 repositories repo public ID params
func (o *GetAPIV3RepositoriesRepoPublicIDParams) WithContext(ctx context.Context) *GetAPIV3RepositoriesRepoPublicIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API v3 repositories repo public ID params
func (o *GetAPIV3RepositoriesRepoPublicIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API v3 repositories repo public ID params
func (o *GetAPIV3RepositoriesRepoPublicIDParams) WithHTTPClient(client *http.Client) *GetAPIV3RepositoriesRepoPublicIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API v3 repositories repo public ID params
func (o *GetAPIV3RepositoriesRepoPublicIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRepoPublicID adds the repoPublicID to the get API v3 repositories repo public ID params
func (o *GetAPIV3RepositoriesRepoPublicIDParams) WithRepoPublicID(repoPublicID int64) *GetAPIV3RepositoriesRepoPublicIDParams {
	o.SetRepoPublicID(repoPublicID)
	return o
}

// SetRepoPublicID adds the repoPublicId to the get API v3 repositories repo public ID params
func (o *GetAPIV3RepositoriesRepoPublicIDParams) SetRepoPublicID(repoPublicID int64) {
	o.RepoPublicID = repoPublicID
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIV3RepositoriesRepoPublicIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param repo-public-id
	if err := r.SetPathParam("repo-public-id", swag.FormatInt64(o.RepoPublicID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
