// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAPIV3LinkedFilesParams creates a new GetAPIV3LinkedFilesParams object
// with the default values initialized.
func NewGetAPIV3LinkedFilesParams() *GetAPIV3LinkedFilesParams {

	return &GetAPIV3LinkedFilesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIV3LinkedFilesParamsWithTimeout creates a new GetAPIV3LinkedFilesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAPIV3LinkedFilesParamsWithTimeout(timeout time.Duration) *GetAPIV3LinkedFilesParams {

	return &GetAPIV3LinkedFilesParams{

		timeout: timeout,
	}
}

// NewGetAPIV3LinkedFilesParamsWithContext creates a new GetAPIV3LinkedFilesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAPIV3LinkedFilesParamsWithContext(ctx context.Context) *GetAPIV3LinkedFilesParams {

	return &GetAPIV3LinkedFilesParams{

		Context: ctx,
	}
}

// NewGetAPIV3LinkedFilesParamsWithHTTPClient creates a new GetAPIV3LinkedFilesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAPIV3LinkedFilesParamsWithHTTPClient(client *http.Client) *GetAPIV3LinkedFilesParams {

	return &GetAPIV3LinkedFilesParams{
		HTTPClient: client,
	}
}

/*GetAPIV3LinkedFilesParams contains all the parameters to send to the API endpoint
for the get API v3 linked files operation typically these are written to a http.Request
*/
type GetAPIV3LinkedFilesParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get API v3 linked files params
func (o *GetAPIV3LinkedFilesParams) WithTimeout(timeout time.Duration) *GetAPIV3LinkedFilesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API v3 linked files params
func (o *GetAPIV3LinkedFilesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API v3 linked files params
func (o *GetAPIV3LinkedFilesParams) WithContext(ctx context.Context) *GetAPIV3LinkedFilesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API v3 linked files params
func (o *GetAPIV3LinkedFilesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API v3 linked files params
func (o *GetAPIV3LinkedFilesParams) WithHTTPClient(client *http.Client) *GetAPIV3LinkedFilesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API v3 linked files params
func (o *GetAPIV3LinkedFilesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIV3LinkedFilesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
