// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/bateau-eng/chapi/pkg/models"
)

// GetAPIV3StoryLinksStoryLinkPublicIDReader is a Reader for the GetAPIV3StoryLinksStoryLinkPublicID structure.
type GetAPIV3StoryLinksStoryLinkPublicIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV3StoryLinksStoryLinkPublicIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIV3StoryLinksStoryLinkPublicIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetAPIV3StoryLinksStoryLinkPublicIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetAPIV3StoryLinksStoryLinkPublicIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewGetAPIV3StoryLinksStoryLinkPublicIDUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAPIV3StoryLinksStoryLinkPublicIDOK creates a GetAPIV3StoryLinksStoryLinkPublicIDOK with default headers values
func NewGetAPIV3StoryLinksStoryLinkPublicIDOK() *GetAPIV3StoryLinksStoryLinkPublicIDOK {
	return &GetAPIV3StoryLinksStoryLinkPublicIDOK{}
}

/*GetAPIV3StoryLinksStoryLinkPublicIDOK handles this case with default header values.

Resource
*/
type GetAPIV3StoryLinksStoryLinkPublicIDOK struct {
	Payload *models.StoryLink
}

func (o *GetAPIV3StoryLinksStoryLinkPublicIDOK) Error() string {
	return fmt.Sprintf("[GET /api/v3/story-links/{story-link-public-id}][%d] getApiV3StoryLinksStoryLinkPublicIdOK  %+v", 200, o.Payload)
}

func (o *GetAPIV3StoryLinksStoryLinkPublicIDOK) GetPayload() *models.StoryLink {
	return o.Payload
}

func (o *GetAPIV3StoryLinksStoryLinkPublicIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StoryLink)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIV3StoryLinksStoryLinkPublicIDBadRequest creates a GetAPIV3StoryLinksStoryLinkPublicIDBadRequest with default headers values
func NewGetAPIV3StoryLinksStoryLinkPublicIDBadRequest() *GetAPIV3StoryLinksStoryLinkPublicIDBadRequest {
	return &GetAPIV3StoryLinksStoryLinkPublicIDBadRequest{}
}

/*GetAPIV3StoryLinksStoryLinkPublicIDBadRequest handles this case with default header values.

Schema mismatch
*/
type GetAPIV3StoryLinksStoryLinkPublicIDBadRequest struct {
}

func (o *GetAPIV3StoryLinksStoryLinkPublicIDBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/v3/story-links/{story-link-public-id}][%d] getApiV3StoryLinksStoryLinkPublicIdBadRequest ", 400)
}

func (o *GetAPIV3StoryLinksStoryLinkPublicIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAPIV3StoryLinksStoryLinkPublicIDNotFound creates a GetAPIV3StoryLinksStoryLinkPublicIDNotFound with default headers values
func NewGetAPIV3StoryLinksStoryLinkPublicIDNotFound() *GetAPIV3StoryLinksStoryLinkPublicIDNotFound {
	return &GetAPIV3StoryLinksStoryLinkPublicIDNotFound{}
}

/*GetAPIV3StoryLinksStoryLinkPublicIDNotFound handles this case with default header values.

Resource does not exist
*/
type GetAPIV3StoryLinksStoryLinkPublicIDNotFound struct {
}

func (o *GetAPIV3StoryLinksStoryLinkPublicIDNotFound) Error() string {
	return fmt.Sprintf("[GET /api/v3/story-links/{story-link-public-id}][%d] getApiV3StoryLinksStoryLinkPublicIdNotFound ", 404)
}

func (o *GetAPIV3StoryLinksStoryLinkPublicIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAPIV3StoryLinksStoryLinkPublicIDUnprocessableEntity creates a GetAPIV3StoryLinksStoryLinkPublicIDUnprocessableEntity with default headers values
func NewGetAPIV3StoryLinksStoryLinkPublicIDUnprocessableEntity() *GetAPIV3StoryLinksStoryLinkPublicIDUnprocessableEntity {
	return &GetAPIV3StoryLinksStoryLinkPublicIDUnprocessableEntity{}
}

/*GetAPIV3StoryLinksStoryLinkPublicIDUnprocessableEntity handles this case with default header values.

Unprocessable
*/
type GetAPIV3StoryLinksStoryLinkPublicIDUnprocessableEntity struct {
}

func (o *GetAPIV3StoryLinksStoryLinkPublicIDUnprocessableEntity) Error() string {
	return fmt.Sprintf("[GET /api/v3/story-links/{story-link-public-id}][%d] getApiV3StoryLinksStoryLinkPublicIdUnprocessableEntity ", 422)
}

func (o *GetAPIV3StoryLinksStoryLinkPublicIDUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
