// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/bateau-eng/chapi/pkg/models"
)

// GetAPIV3EpicsEpicPublicIDReader is a Reader for the GetAPIV3EpicsEpicPublicID structure.
type GetAPIV3EpicsEpicPublicIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV3EpicsEpicPublicIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIV3EpicsEpicPublicIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetAPIV3EpicsEpicPublicIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetAPIV3EpicsEpicPublicIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewGetAPIV3EpicsEpicPublicIDUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAPIV3EpicsEpicPublicIDOK creates a GetAPIV3EpicsEpicPublicIDOK with default headers values
func NewGetAPIV3EpicsEpicPublicIDOK() *GetAPIV3EpicsEpicPublicIDOK {
	return &GetAPIV3EpicsEpicPublicIDOK{}
}

/*GetAPIV3EpicsEpicPublicIDOK handles this case with default header values.

Resource
*/
type GetAPIV3EpicsEpicPublicIDOK struct {
	Payload *models.Epic
}

func (o *GetAPIV3EpicsEpicPublicIDOK) Error() string {
	return fmt.Sprintf("[GET /api/v3/epics/{epic-public-id}][%d] getApiV3EpicsEpicPublicIdOK  %+v", 200, o.Payload)
}

func (o *GetAPIV3EpicsEpicPublicIDOK) GetPayload() *models.Epic {
	return o.Payload
}

func (o *GetAPIV3EpicsEpicPublicIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Epic)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIV3EpicsEpicPublicIDBadRequest creates a GetAPIV3EpicsEpicPublicIDBadRequest with default headers values
func NewGetAPIV3EpicsEpicPublicIDBadRequest() *GetAPIV3EpicsEpicPublicIDBadRequest {
	return &GetAPIV3EpicsEpicPublicIDBadRequest{}
}

/*GetAPIV3EpicsEpicPublicIDBadRequest handles this case with default header values.

Schema mismatch
*/
type GetAPIV3EpicsEpicPublicIDBadRequest struct {
}

func (o *GetAPIV3EpicsEpicPublicIDBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/v3/epics/{epic-public-id}][%d] getApiV3EpicsEpicPublicIdBadRequest ", 400)
}

func (o *GetAPIV3EpicsEpicPublicIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAPIV3EpicsEpicPublicIDNotFound creates a GetAPIV3EpicsEpicPublicIDNotFound with default headers values
func NewGetAPIV3EpicsEpicPublicIDNotFound() *GetAPIV3EpicsEpicPublicIDNotFound {
	return &GetAPIV3EpicsEpicPublicIDNotFound{}
}

/*GetAPIV3EpicsEpicPublicIDNotFound handles this case with default header values.

Resource does not exist
*/
type GetAPIV3EpicsEpicPublicIDNotFound struct {
}

func (o *GetAPIV3EpicsEpicPublicIDNotFound) Error() string {
	return fmt.Sprintf("[GET /api/v3/epics/{epic-public-id}][%d] getApiV3EpicsEpicPublicIdNotFound ", 404)
}

func (o *GetAPIV3EpicsEpicPublicIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAPIV3EpicsEpicPublicIDUnprocessableEntity creates a GetAPIV3EpicsEpicPublicIDUnprocessableEntity with default headers values
func NewGetAPIV3EpicsEpicPublicIDUnprocessableEntity() *GetAPIV3EpicsEpicPublicIDUnprocessableEntity {
	return &GetAPIV3EpicsEpicPublicIDUnprocessableEntity{}
}

/*GetAPIV3EpicsEpicPublicIDUnprocessableEntity handles this case with default header values.

Unprocessable
*/
type GetAPIV3EpicsEpicPublicIDUnprocessableEntity struct {
}

func (o *GetAPIV3EpicsEpicPublicIDUnprocessableEntity) Error() string {
	return fmt.Sprintf("[GET /api/v3/epics/{epic-public-id}][%d] getApiV3EpicsEpicPublicIdUnprocessableEntity ", 422)
}

func (o *GetAPIV3EpicsEpicPublicIDUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
