// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/bateau-eng/chapi/v0/pkg/models"
)

// NewGetAPIV3LabelsLabelPublicIDStoriesParams creates a new GetAPIV3LabelsLabelPublicIDStoriesParams object
// with the default values initialized.
func NewGetAPIV3LabelsLabelPublicIDStoriesParams() *GetAPIV3LabelsLabelPublicIDStoriesParams {
	var ()
	return &GetAPIV3LabelsLabelPublicIDStoriesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIV3LabelsLabelPublicIDStoriesParamsWithTimeout creates a new GetAPIV3LabelsLabelPublicIDStoriesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAPIV3LabelsLabelPublicIDStoriesParamsWithTimeout(timeout time.Duration) *GetAPIV3LabelsLabelPublicIDStoriesParams {
	var ()
	return &GetAPIV3LabelsLabelPublicIDStoriesParams{

		timeout: timeout,
	}
}

// NewGetAPIV3LabelsLabelPublicIDStoriesParamsWithContext creates a new GetAPIV3LabelsLabelPublicIDStoriesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAPIV3LabelsLabelPublicIDStoriesParamsWithContext(ctx context.Context) *GetAPIV3LabelsLabelPublicIDStoriesParams {
	var ()
	return &GetAPIV3LabelsLabelPublicIDStoriesParams{

		Context: ctx,
	}
}

// NewGetAPIV3LabelsLabelPublicIDStoriesParamsWithHTTPClient creates a new GetAPIV3LabelsLabelPublicIDStoriesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAPIV3LabelsLabelPublicIDStoriesParamsWithHTTPClient(client *http.Client) *GetAPIV3LabelsLabelPublicIDStoriesParams {
	var ()
	return &GetAPIV3LabelsLabelPublicIDStoriesParams{
		HTTPClient: client,
	}
}

/*GetAPIV3LabelsLabelPublicIDStoriesParams contains all the parameters to send to the API endpoint
for the get API v3 labels label public ID stories operation typically these are written to a http.Request
*/
type GetAPIV3LabelsLabelPublicIDStoriesParams struct {

	/*GetLabelStories*/
	GetLabelStories *models.GetLabelStories
	/*LabelPublicID
	  The unique ID of the Label.

	*/
	LabelPublicID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get API v3 labels label public ID stories params
func (o *GetAPIV3LabelsLabelPublicIDStoriesParams) WithTimeout(timeout time.Duration) *GetAPIV3LabelsLabelPublicIDStoriesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API v3 labels label public ID stories params
func (o *GetAPIV3LabelsLabelPublicIDStoriesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API v3 labels label public ID stories params
func (o *GetAPIV3LabelsLabelPublicIDStoriesParams) WithContext(ctx context.Context) *GetAPIV3LabelsLabelPublicIDStoriesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API v3 labels label public ID stories params
func (o *GetAPIV3LabelsLabelPublicIDStoriesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API v3 labels label public ID stories params
func (o *GetAPIV3LabelsLabelPublicIDStoriesParams) WithHTTPClient(client *http.Client) *GetAPIV3LabelsLabelPublicIDStoriesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API v3 labels label public ID stories params
func (o *GetAPIV3LabelsLabelPublicIDStoriesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithGetLabelStories adds the getLabelStories to the get API v3 labels label public ID stories params
func (o *GetAPIV3LabelsLabelPublicIDStoriesParams) WithGetLabelStories(getLabelStories *models.GetLabelStories) *GetAPIV3LabelsLabelPublicIDStoriesParams {
	o.SetGetLabelStories(getLabelStories)
	return o
}

// SetGetLabelStories adds the getLabelStories to the get API v3 labels label public ID stories params
func (o *GetAPIV3LabelsLabelPublicIDStoriesParams) SetGetLabelStories(getLabelStories *models.GetLabelStories) {
	o.GetLabelStories = getLabelStories
}

// WithLabelPublicID adds the labelPublicID to the get API v3 labels label public ID stories params
func (o *GetAPIV3LabelsLabelPublicIDStoriesParams) WithLabelPublicID(labelPublicID int64) *GetAPIV3LabelsLabelPublicIDStoriesParams {
	o.SetLabelPublicID(labelPublicID)
	return o
}

// SetLabelPublicID adds the labelPublicId to the get API v3 labels label public ID stories params
func (o *GetAPIV3LabelsLabelPublicIDStoriesParams) SetLabelPublicID(labelPublicID int64) {
	o.LabelPublicID = labelPublicID
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIV3LabelsLabelPublicIDStoriesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.GetLabelStories != nil {
		if err := r.SetBodyParam(o.GetLabelStories); err != nil {
			return err
		}
	}

	// path param label-public-id
	if err := r.SetPathParam("label-public-id", swag.FormatInt64(o.LabelPublicID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
