// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/bateau-eng/chapi/v0/pkg/models"
)

// GetAPIV3MembersReader is a Reader for the GetAPIV3Members structure.
type GetAPIV3MembersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV3MembersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIV3MembersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetAPIV3MembersBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetAPIV3MembersNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewGetAPIV3MembersUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAPIV3MembersOK creates a GetAPIV3MembersOK with default headers values
func NewGetAPIV3MembersOK() *GetAPIV3MembersOK {
	return &GetAPIV3MembersOK{}
}

/*GetAPIV3MembersOK handles this case with default header values.

Resource
*/
type GetAPIV3MembersOK struct {
	Payload []*models.Member
}

func (o *GetAPIV3MembersOK) Error() string {
	return fmt.Sprintf("[GET /api/v3/members][%d] getApiV3MembersOK  %+v", 200, o.Payload)
}

func (o *GetAPIV3MembersOK) GetPayload() []*models.Member {
	return o.Payload
}

func (o *GetAPIV3MembersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIV3MembersBadRequest creates a GetAPIV3MembersBadRequest with default headers values
func NewGetAPIV3MembersBadRequest() *GetAPIV3MembersBadRequest {
	return &GetAPIV3MembersBadRequest{}
}

/*GetAPIV3MembersBadRequest handles this case with default header values.

Schema mismatch
*/
type GetAPIV3MembersBadRequest struct {
}

func (o *GetAPIV3MembersBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/v3/members][%d] getApiV3MembersBadRequest ", 400)
}

func (o *GetAPIV3MembersBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAPIV3MembersNotFound creates a GetAPIV3MembersNotFound with default headers values
func NewGetAPIV3MembersNotFound() *GetAPIV3MembersNotFound {
	return &GetAPIV3MembersNotFound{}
}

/*GetAPIV3MembersNotFound handles this case with default header values.

Resource does not exist
*/
type GetAPIV3MembersNotFound struct {
}

func (o *GetAPIV3MembersNotFound) Error() string {
	return fmt.Sprintf("[GET /api/v3/members][%d] getApiV3MembersNotFound ", 404)
}

func (o *GetAPIV3MembersNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAPIV3MembersUnprocessableEntity creates a GetAPIV3MembersUnprocessableEntity with default headers values
func NewGetAPIV3MembersUnprocessableEntity() *GetAPIV3MembersUnprocessableEntity {
	return &GetAPIV3MembersUnprocessableEntity{}
}

/*GetAPIV3MembersUnprocessableEntity handles this case with default header values.

Unprocessable
*/
type GetAPIV3MembersUnprocessableEntity struct {
}

func (o *GetAPIV3MembersUnprocessableEntity) Error() string {
	return fmt.Sprintf("[GET /api/v3/members][%d] getApiV3MembersUnprocessableEntity ", 422)
}

func (o *GetAPIV3MembersUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
