// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/bateau-eng/chapi/v0/pkg/models"
)

// GetAPIV3TeamsReader is a Reader for the GetAPIV3Teams structure.
type GetAPIV3TeamsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV3TeamsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIV3TeamsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetAPIV3TeamsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetAPIV3TeamsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewGetAPIV3TeamsUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAPIV3TeamsOK creates a GetAPIV3TeamsOK with default headers values
func NewGetAPIV3TeamsOK() *GetAPIV3TeamsOK {
	return &GetAPIV3TeamsOK{}
}

/*GetAPIV3TeamsOK handles this case with default header values.

Resource
*/
type GetAPIV3TeamsOK struct {
	Payload []*models.Team
}

func (o *GetAPIV3TeamsOK) Error() string {
	return fmt.Sprintf("[GET /api/v3/teams][%d] getApiV3TeamsOK  %+v", 200, o.Payload)
}

func (o *GetAPIV3TeamsOK) GetPayload() []*models.Team {
	return o.Payload
}

func (o *GetAPIV3TeamsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIV3TeamsBadRequest creates a GetAPIV3TeamsBadRequest with default headers values
func NewGetAPIV3TeamsBadRequest() *GetAPIV3TeamsBadRequest {
	return &GetAPIV3TeamsBadRequest{}
}

/*GetAPIV3TeamsBadRequest handles this case with default header values.

Schema mismatch
*/
type GetAPIV3TeamsBadRequest struct {
}

func (o *GetAPIV3TeamsBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/v3/teams][%d] getApiV3TeamsBadRequest ", 400)
}

func (o *GetAPIV3TeamsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAPIV3TeamsNotFound creates a GetAPIV3TeamsNotFound with default headers values
func NewGetAPIV3TeamsNotFound() *GetAPIV3TeamsNotFound {
	return &GetAPIV3TeamsNotFound{}
}

/*GetAPIV3TeamsNotFound handles this case with default header values.

Resource does not exist
*/
type GetAPIV3TeamsNotFound struct {
}

func (o *GetAPIV3TeamsNotFound) Error() string {
	return fmt.Sprintf("[GET /api/v3/teams][%d] getApiV3TeamsNotFound ", 404)
}

func (o *GetAPIV3TeamsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAPIV3TeamsUnprocessableEntity creates a GetAPIV3TeamsUnprocessableEntity with default headers values
func NewGetAPIV3TeamsUnprocessableEntity() *GetAPIV3TeamsUnprocessableEntity {
	return &GetAPIV3TeamsUnprocessableEntity{}
}

/*GetAPIV3TeamsUnprocessableEntity handles this case with default header values.

Unprocessable
*/
type GetAPIV3TeamsUnprocessableEntity struct {
}

func (o *GetAPIV3TeamsUnprocessableEntity) Error() string {
	return fmt.Sprintf("[GET /api/v3/teams][%d] getApiV3TeamsUnprocessableEntity ", 422)
}

func (o *GetAPIV3TeamsUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
