// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/bateau-eng/chapi/v0/pkg/models"
)

// GetAPIV3SearchEpicsReader is a Reader for the GetAPIV3SearchEpics structure.
type GetAPIV3SearchEpicsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV3SearchEpicsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIV3SearchEpicsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetAPIV3SearchEpicsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetAPIV3SearchEpicsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewGetAPIV3SearchEpicsUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAPIV3SearchEpicsOK creates a GetAPIV3SearchEpicsOK with default headers values
func NewGetAPIV3SearchEpicsOK() *GetAPIV3SearchEpicsOK {
	return &GetAPIV3SearchEpicsOK{}
}

/*GetAPIV3SearchEpicsOK handles this case with default header values.

Resource
*/
type GetAPIV3SearchEpicsOK struct {
	Payload *models.EpicSearchResults
}

func (o *GetAPIV3SearchEpicsOK) Error() string {
	return fmt.Sprintf("[GET /api/v3/search/epics][%d] getApiV3SearchEpicsOK  %+v", 200, o.Payload)
}

func (o *GetAPIV3SearchEpicsOK) GetPayload() *models.EpicSearchResults {
	return o.Payload
}

func (o *GetAPIV3SearchEpicsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EpicSearchResults)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIV3SearchEpicsBadRequest creates a GetAPIV3SearchEpicsBadRequest with default headers values
func NewGetAPIV3SearchEpicsBadRequest() *GetAPIV3SearchEpicsBadRequest {
	return &GetAPIV3SearchEpicsBadRequest{}
}

/*GetAPIV3SearchEpicsBadRequest handles this case with default header values.

**Either:** (1) Schema mismatch **or** (2) Maximum of 1000 search results exceeded
 */
type GetAPIV3SearchEpicsBadRequest struct {
	Payload *models.MaxSearchResultsExceededError
}

func (o *GetAPIV3SearchEpicsBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/v3/search/epics][%d] getApiV3SearchEpicsBadRequest  %+v", 400, o.Payload)
}

func (o *GetAPIV3SearchEpicsBadRequest) GetPayload() *models.MaxSearchResultsExceededError {
	return o.Payload
}

func (o *GetAPIV3SearchEpicsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MaxSearchResultsExceededError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIV3SearchEpicsNotFound creates a GetAPIV3SearchEpicsNotFound with default headers values
func NewGetAPIV3SearchEpicsNotFound() *GetAPIV3SearchEpicsNotFound {
	return &GetAPIV3SearchEpicsNotFound{}
}

/*GetAPIV3SearchEpicsNotFound handles this case with default header values.

Resource does not exist
*/
type GetAPIV3SearchEpicsNotFound struct {
}

func (o *GetAPIV3SearchEpicsNotFound) Error() string {
	return fmt.Sprintf("[GET /api/v3/search/epics][%d] getApiV3SearchEpicsNotFound ", 404)
}

func (o *GetAPIV3SearchEpicsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAPIV3SearchEpicsUnprocessableEntity creates a GetAPIV3SearchEpicsUnprocessableEntity with default headers values
func NewGetAPIV3SearchEpicsUnprocessableEntity() *GetAPIV3SearchEpicsUnprocessableEntity {
	return &GetAPIV3SearchEpicsUnprocessableEntity{}
}

/*GetAPIV3SearchEpicsUnprocessableEntity handles this case with default header values.

Unprocessable
*/
type GetAPIV3SearchEpicsUnprocessableEntity struct {
}

func (o *GetAPIV3SearchEpicsUnprocessableEntity) Error() string {
	return fmt.Sprintf("[GET /api/v3/search/epics][%d] getApiV3SearchEpicsUnprocessableEntity ", 422)
}

func (o *GetAPIV3SearchEpicsUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
