// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/bateau-eng/chapi/v0/pkg/models"
)

// GetAPIV3LinkedFilesReader is a Reader for the GetAPIV3LinkedFiles structure.
type GetAPIV3LinkedFilesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV3LinkedFilesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIV3LinkedFilesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetAPIV3LinkedFilesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetAPIV3LinkedFilesNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewGetAPIV3LinkedFilesUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAPIV3LinkedFilesOK creates a GetAPIV3LinkedFilesOK with default headers values
func NewGetAPIV3LinkedFilesOK() *GetAPIV3LinkedFilesOK {
	return &GetAPIV3LinkedFilesOK{}
}

/*GetAPIV3LinkedFilesOK handles this case with default header values.

Resource
*/
type GetAPIV3LinkedFilesOK struct {
	Payload []*models.LinkedFile
}

func (o *GetAPIV3LinkedFilesOK) Error() string {
	return fmt.Sprintf("[GET /api/v3/linked-files][%d] getApiV3LinkedFilesOK  %+v", 200, o.Payload)
}

func (o *GetAPIV3LinkedFilesOK) GetPayload() []*models.LinkedFile {
	return o.Payload
}

func (o *GetAPIV3LinkedFilesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIV3LinkedFilesBadRequest creates a GetAPIV3LinkedFilesBadRequest with default headers values
func NewGetAPIV3LinkedFilesBadRequest() *GetAPIV3LinkedFilesBadRequest {
	return &GetAPIV3LinkedFilesBadRequest{}
}

/*GetAPIV3LinkedFilesBadRequest handles this case with default header values.

Schema mismatch
*/
type GetAPIV3LinkedFilesBadRequest struct {
}

func (o *GetAPIV3LinkedFilesBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/v3/linked-files][%d] getApiV3LinkedFilesBadRequest ", 400)
}

func (o *GetAPIV3LinkedFilesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAPIV3LinkedFilesNotFound creates a GetAPIV3LinkedFilesNotFound with default headers values
func NewGetAPIV3LinkedFilesNotFound() *GetAPIV3LinkedFilesNotFound {
	return &GetAPIV3LinkedFilesNotFound{}
}

/*GetAPIV3LinkedFilesNotFound handles this case with default header values.

Resource does not exist
*/
type GetAPIV3LinkedFilesNotFound struct {
}

func (o *GetAPIV3LinkedFilesNotFound) Error() string {
	return fmt.Sprintf("[GET /api/v3/linked-files][%d] getApiV3LinkedFilesNotFound ", 404)
}

func (o *GetAPIV3LinkedFilesNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAPIV3LinkedFilesUnprocessableEntity creates a GetAPIV3LinkedFilesUnprocessableEntity with default headers values
func NewGetAPIV3LinkedFilesUnprocessableEntity() *GetAPIV3LinkedFilesUnprocessableEntity {
	return &GetAPIV3LinkedFilesUnprocessableEntity{}
}

/*GetAPIV3LinkedFilesUnprocessableEntity handles this case with default header values.

Unprocessable
*/
type GetAPIV3LinkedFilesUnprocessableEntity struct {
}

func (o *GetAPIV3LinkedFilesUnprocessableEntity) Error() string {
	return fmt.Sprintf("[GET /api/v3/linked-files][%d] getApiV3LinkedFilesUnprocessableEntity ", 422)
}

func (o *GetAPIV3LinkedFilesUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
