// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/bateau-eng/chapi/pkg/models"
)

// NewGetAPIV3LabelsParams creates a new GetAPIV3LabelsParams object
// with the default values initialized.
func NewGetAPIV3LabelsParams() *GetAPIV3LabelsParams {
	var ()
	return &GetAPIV3LabelsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIV3LabelsParamsWithTimeout creates a new GetAPIV3LabelsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAPIV3LabelsParamsWithTimeout(timeout time.Duration) *GetAPIV3LabelsParams {
	var ()
	return &GetAPIV3LabelsParams{

		timeout: timeout,
	}
}

// NewGetAPIV3LabelsParamsWithContext creates a new GetAPIV3LabelsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAPIV3LabelsParamsWithContext(ctx context.Context) *GetAPIV3LabelsParams {
	var ()
	return &GetAPIV3LabelsParams{

		Context: ctx,
	}
}

// NewGetAPIV3LabelsParamsWithHTTPClient creates a new GetAPIV3LabelsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAPIV3LabelsParamsWithHTTPClient(client *http.Client) *GetAPIV3LabelsParams {
	var ()
	return &GetAPIV3LabelsParams{
		HTTPClient: client,
	}
}

/*GetAPIV3LabelsParams contains all the parameters to send to the API endpoint
for the get API v3 labels operation typically these are written to a http.Request
*/
type GetAPIV3LabelsParams struct {

	/*ListLabels*/
	ListLabels *models.ListLabels

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get API v3 labels params
func (o *GetAPIV3LabelsParams) WithTimeout(timeout time.Duration) *GetAPIV3LabelsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API v3 labels params
func (o *GetAPIV3LabelsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API v3 labels params
func (o *GetAPIV3LabelsParams) WithContext(ctx context.Context) *GetAPIV3LabelsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API v3 labels params
func (o *GetAPIV3LabelsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API v3 labels params
func (o *GetAPIV3LabelsParams) WithHTTPClient(client *http.Client) *GetAPIV3LabelsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API v3 labels params
func (o *GetAPIV3LabelsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithListLabels adds the listLabels to the get API v3 labels params
func (o *GetAPIV3LabelsParams) WithListLabels(listLabels *models.ListLabels) *GetAPIV3LabelsParams {
	o.SetListLabels(listLabels)
	return o
}

// SetListLabels adds the listLabels to the get API v3 labels params
func (o *GetAPIV3LabelsParams) SetListLabels(listLabels *models.ListLabels) {
	o.ListLabels = listLabels
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIV3LabelsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ListLabels != nil {
		if err := r.SetBodyParam(o.ListLabels); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
