// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetAPIV3EpicsEpicPublicIDParams creates a new GetAPIV3EpicsEpicPublicIDParams object
// with the default values initialized.
func NewGetAPIV3EpicsEpicPublicIDParams() *GetAPIV3EpicsEpicPublicIDParams {
	var ()
	return &GetAPIV3EpicsEpicPublicIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIV3EpicsEpicPublicIDParamsWithTimeout creates a new GetAPIV3EpicsEpicPublicIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAPIV3EpicsEpicPublicIDParamsWithTimeout(timeout time.Duration) *GetAPIV3EpicsEpicPublicIDParams {
	var ()
	return &GetAPIV3EpicsEpicPublicIDParams{

		timeout: timeout,
	}
}

// NewGetAPIV3EpicsEpicPublicIDParamsWithContext creates a new GetAPIV3EpicsEpicPublicIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAPIV3EpicsEpicPublicIDParamsWithContext(ctx context.Context) *GetAPIV3EpicsEpicPublicIDParams {
	var ()
	return &GetAPIV3EpicsEpicPublicIDParams{

		Context: ctx,
	}
}

// NewGetAPIV3EpicsEpicPublicIDParamsWithHTTPClient creates a new GetAPIV3EpicsEpicPublicIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAPIV3EpicsEpicPublicIDParamsWithHTTPClient(client *http.Client) *GetAPIV3EpicsEpicPublicIDParams {
	var ()
	return &GetAPIV3EpicsEpicPublicIDParams{
		HTTPClient: client,
	}
}

/*GetAPIV3EpicsEpicPublicIDParams contains all the parameters to send to the API endpoint
for the get API v3 epics epic public ID operation typically these are written to a http.Request
*/
type GetAPIV3EpicsEpicPublicIDParams struct {

	/*EpicPublicID
	  The unique ID of the Epic.

	*/
	EpicPublicID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get API v3 epics epic public ID params
func (o *GetAPIV3EpicsEpicPublicIDParams) WithTimeout(timeout time.Duration) *GetAPIV3EpicsEpicPublicIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API v3 epics epic public ID params
func (o *GetAPIV3EpicsEpicPublicIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API v3 epics epic public ID params
func (o *GetAPIV3EpicsEpicPublicIDParams) WithContext(ctx context.Context) *GetAPIV3EpicsEpicPublicIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API v3 epics epic public ID params
func (o *GetAPIV3EpicsEpicPublicIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API v3 epics epic public ID params
func (o *GetAPIV3EpicsEpicPublicIDParams) WithHTTPClient(client *http.Client) *GetAPIV3EpicsEpicPublicIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API v3 epics epic public ID params
func (o *GetAPIV3EpicsEpicPublicIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEpicPublicID adds the epicPublicID to the get API v3 epics epic public ID params
func (o *GetAPIV3EpicsEpicPublicIDParams) WithEpicPublicID(epicPublicID int64) *GetAPIV3EpicsEpicPublicIDParams {
	o.SetEpicPublicID(epicPublicID)
	return o
}

// SetEpicPublicID adds the epicPublicId to the get API v3 epics epic public ID params
func (o *GetAPIV3EpicsEpicPublicIDParams) SetEpicPublicID(epicPublicID int64) {
	o.EpicPublicID = epicPublicID
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIV3EpicsEpicPublicIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param epic-public-id
	if err := r.SetPathParam("epic-public-id", swag.FormatInt64(o.EpicPublicID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
