// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/bateau-eng/chapi/pkg/models"
)

// GetAPIV3SearchStoriesReader is a Reader for the GetAPIV3SearchStories structure.
type GetAPIV3SearchStoriesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV3SearchStoriesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIV3SearchStoriesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetAPIV3SearchStoriesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetAPIV3SearchStoriesNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewGetAPIV3SearchStoriesUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAPIV3SearchStoriesOK creates a GetAPIV3SearchStoriesOK with default headers values
func NewGetAPIV3SearchStoriesOK() *GetAPIV3SearchStoriesOK {
	return &GetAPIV3SearchStoriesOK{}
}

/*GetAPIV3SearchStoriesOK handles this case with default header values.

Resource
*/
type GetAPIV3SearchStoriesOK struct {
	Payload *models.StorySearchResults
}

func (o *GetAPIV3SearchStoriesOK) Error() string {
	return fmt.Sprintf("[GET /api/v3/search/stories][%d] getApiV3SearchStoriesOK  %+v", 200, o.Payload)
}

func (o *GetAPIV3SearchStoriesOK) GetPayload() *models.StorySearchResults {
	return o.Payload
}

func (o *GetAPIV3SearchStoriesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StorySearchResults)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIV3SearchStoriesBadRequest creates a GetAPIV3SearchStoriesBadRequest with default headers values
func NewGetAPIV3SearchStoriesBadRequest() *GetAPIV3SearchStoriesBadRequest {
	return &GetAPIV3SearchStoriesBadRequest{}
}

/*GetAPIV3SearchStoriesBadRequest handles this case with default header values.

**Either:** (1) Schema mismatch **or** (2) Maximum of 1000 search results exceeded
 */
type GetAPIV3SearchStoriesBadRequest struct {
	Payload *models.MaxSearchResultsExceededError
}

func (o *GetAPIV3SearchStoriesBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/v3/search/stories][%d] getApiV3SearchStoriesBadRequest  %+v", 400, o.Payload)
}

func (o *GetAPIV3SearchStoriesBadRequest) GetPayload() *models.MaxSearchResultsExceededError {
	return o.Payload
}

func (o *GetAPIV3SearchStoriesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MaxSearchResultsExceededError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIV3SearchStoriesNotFound creates a GetAPIV3SearchStoriesNotFound with default headers values
func NewGetAPIV3SearchStoriesNotFound() *GetAPIV3SearchStoriesNotFound {
	return &GetAPIV3SearchStoriesNotFound{}
}

/*GetAPIV3SearchStoriesNotFound handles this case with default header values.

Resource does not exist
*/
type GetAPIV3SearchStoriesNotFound struct {
}

func (o *GetAPIV3SearchStoriesNotFound) Error() string {
	return fmt.Sprintf("[GET /api/v3/search/stories][%d] getApiV3SearchStoriesNotFound ", 404)
}

func (o *GetAPIV3SearchStoriesNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAPIV3SearchStoriesUnprocessableEntity creates a GetAPIV3SearchStoriesUnprocessableEntity with default headers values
func NewGetAPIV3SearchStoriesUnprocessableEntity() *GetAPIV3SearchStoriesUnprocessableEntity {
	return &GetAPIV3SearchStoriesUnprocessableEntity{}
}

/*GetAPIV3SearchStoriesUnprocessableEntity handles this case with default header values.

Unprocessable
*/
type GetAPIV3SearchStoriesUnprocessableEntity struct {
}

func (o *GetAPIV3SearchStoriesUnprocessableEntity) Error() string {
	return fmt.Sprintf("[GET /api/v3/search/stories][%d] getApiV3SearchStoriesUnprocessableEntity ", 422)
}

func (o *GetAPIV3SearchStoriesUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
