// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAPIV3EntityTemplatesParams creates a new GetAPIV3EntityTemplatesParams object
// with the default values initialized.
func NewGetAPIV3EntityTemplatesParams() *GetAPIV3EntityTemplatesParams {

	return &GetAPIV3EntityTemplatesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIV3EntityTemplatesParamsWithTimeout creates a new GetAPIV3EntityTemplatesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAPIV3EntityTemplatesParamsWithTimeout(timeout time.Duration) *GetAPIV3EntityTemplatesParams {

	return &GetAPIV3EntityTemplatesParams{

		timeout: timeout,
	}
}

// NewGetAPIV3EntityTemplatesParamsWithContext creates a new GetAPIV3EntityTemplatesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAPIV3EntityTemplatesParamsWithContext(ctx context.Context) *GetAPIV3EntityTemplatesParams {

	return &GetAPIV3EntityTemplatesParams{

		Context: ctx,
	}
}

// NewGetAPIV3EntityTemplatesParamsWithHTTPClient creates a new GetAPIV3EntityTemplatesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAPIV3EntityTemplatesParamsWithHTTPClient(client *http.Client) *GetAPIV3EntityTemplatesParams {

	return &GetAPIV3EntityTemplatesParams{
		HTTPClient: client,
	}
}

/*GetAPIV3EntityTemplatesParams contains all the parameters to send to the API endpoint
for the get API v3 entity templates operation typically these are written to a http.Request
*/
type GetAPIV3EntityTemplatesParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get API v3 entity templates params
func (o *GetAPIV3EntityTemplatesParams) WithTimeout(timeout time.Duration) *GetAPIV3EntityTemplatesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API v3 entity templates params
func (o *GetAPIV3EntityTemplatesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API v3 entity templates params
func (o *GetAPIV3EntityTemplatesParams) WithContext(ctx context.Context) *GetAPIV3EntityTemplatesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API v3 entity templates params
func (o *GetAPIV3EntityTemplatesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API v3 entity templates params
func (o *GetAPIV3EntityTemplatesParams) WithHTTPClient(client *http.Client) *GetAPIV3EntityTemplatesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API v3 entity templates params
func (o *GetAPIV3EntityTemplatesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIV3EntityTemplatesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
