// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/bateau-eng/chapi/pkg/models"
)

// GetAPIV3RepositoriesRepoPublicIDReader is a Reader for the GetAPIV3RepositoriesRepoPublicID structure.
type GetAPIV3RepositoriesRepoPublicIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV3RepositoriesRepoPublicIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIV3RepositoriesRepoPublicIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetAPIV3RepositoriesRepoPublicIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetAPIV3RepositoriesRepoPublicIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewGetAPIV3RepositoriesRepoPublicIDUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAPIV3RepositoriesRepoPublicIDOK creates a GetAPIV3RepositoriesRepoPublicIDOK with default headers values
func NewGetAPIV3RepositoriesRepoPublicIDOK() *GetAPIV3RepositoriesRepoPublicIDOK {
	return &GetAPIV3RepositoriesRepoPublicIDOK{}
}

/*GetAPIV3RepositoriesRepoPublicIDOK handles this case with default header values.

Resource
*/
type GetAPIV3RepositoriesRepoPublicIDOK struct {
	Payload *models.Repository
}

func (o *GetAPIV3RepositoriesRepoPublicIDOK) Error() string {
	return fmt.Sprintf("[GET /api/v3/repositories/{repo-public-id}][%d] getApiV3RepositoriesRepoPublicIdOK  %+v", 200, o.Payload)
}

func (o *GetAPIV3RepositoriesRepoPublicIDOK) GetPayload() *models.Repository {
	return o.Payload
}

func (o *GetAPIV3RepositoriesRepoPublicIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Repository)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIV3RepositoriesRepoPublicIDBadRequest creates a GetAPIV3RepositoriesRepoPublicIDBadRequest with default headers values
func NewGetAPIV3RepositoriesRepoPublicIDBadRequest() *GetAPIV3RepositoriesRepoPublicIDBadRequest {
	return &GetAPIV3RepositoriesRepoPublicIDBadRequest{}
}

/*GetAPIV3RepositoriesRepoPublicIDBadRequest handles this case with default header values.

Schema mismatch
*/
type GetAPIV3RepositoriesRepoPublicIDBadRequest struct {
}

func (o *GetAPIV3RepositoriesRepoPublicIDBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/v3/repositories/{repo-public-id}][%d] getApiV3RepositoriesRepoPublicIdBadRequest ", 400)
}

func (o *GetAPIV3RepositoriesRepoPublicIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAPIV3RepositoriesRepoPublicIDNotFound creates a GetAPIV3RepositoriesRepoPublicIDNotFound with default headers values
func NewGetAPIV3RepositoriesRepoPublicIDNotFound() *GetAPIV3RepositoriesRepoPublicIDNotFound {
	return &GetAPIV3RepositoriesRepoPublicIDNotFound{}
}

/*GetAPIV3RepositoriesRepoPublicIDNotFound handles this case with default header values.

Resource does not exist
*/
type GetAPIV3RepositoriesRepoPublicIDNotFound struct {
}

func (o *GetAPIV3RepositoriesRepoPublicIDNotFound) Error() string {
	return fmt.Sprintf("[GET /api/v3/repositories/{repo-public-id}][%d] getApiV3RepositoriesRepoPublicIdNotFound ", 404)
}

func (o *GetAPIV3RepositoriesRepoPublicIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAPIV3RepositoriesRepoPublicIDUnprocessableEntity creates a GetAPIV3RepositoriesRepoPublicIDUnprocessableEntity with default headers values
func NewGetAPIV3RepositoriesRepoPublicIDUnprocessableEntity() *GetAPIV3RepositoriesRepoPublicIDUnprocessableEntity {
	return &GetAPIV3RepositoriesRepoPublicIDUnprocessableEntity{}
}

/*GetAPIV3RepositoriesRepoPublicIDUnprocessableEntity handles this case with default header values.

Unprocessable
*/
type GetAPIV3RepositoriesRepoPublicIDUnprocessableEntity struct {
}

func (o *GetAPIV3RepositoriesRepoPublicIDUnprocessableEntity) Error() string {
	return fmt.Sprintf("[GET /api/v3/repositories/{repo-public-id}][%d] getApiV3RepositoriesRepoPublicIdUnprocessableEntity ", 422)
}

func (o *GetAPIV3RepositoriesRepoPublicIDUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
