// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/bateau-eng/chapi/pkg/models"
)

// GetAPIV3StoriesStoryPublicIDTasksTaskPublicIDReader is a Reader for the GetAPIV3StoriesStoryPublicIDTasksTaskPublicID structure.
type GetAPIV3StoriesStoryPublicIDTasksTaskPublicIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV3StoriesStoryPublicIDTasksTaskPublicIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIV3StoriesStoryPublicIDTasksTaskPublicIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetAPIV3StoriesStoryPublicIDTasksTaskPublicIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetAPIV3StoriesStoryPublicIDTasksTaskPublicIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewGetAPIV3StoriesStoryPublicIDTasksTaskPublicIDUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAPIV3StoriesStoryPublicIDTasksTaskPublicIDOK creates a GetAPIV3StoriesStoryPublicIDTasksTaskPublicIDOK with default headers values
func NewGetAPIV3StoriesStoryPublicIDTasksTaskPublicIDOK() *GetAPIV3StoriesStoryPublicIDTasksTaskPublicIDOK {
	return &GetAPIV3StoriesStoryPublicIDTasksTaskPublicIDOK{}
}

/*GetAPIV3StoriesStoryPublicIDTasksTaskPublicIDOK handles this case with default header values.

Resource
*/
type GetAPIV3StoriesStoryPublicIDTasksTaskPublicIDOK struct {
	Payload *models.Task
}

func (o *GetAPIV3StoriesStoryPublicIDTasksTaskPublicIDOK) Error() string {
	return fmt.Sprintf("[GET /api/v3/stories/{story-public-id}/tasks/{task-public-id}][%d] getApiV3StoriesStoryPublicIdTasksTaskPublicIdOK  %+v", 200, o.Payload)
}

func (o *GetAPIV3StoriesStoryPublicIDTasksTaskPublicIDOK) GetPayload() *models.Task {
	return o.Payload
}

func (o *GetAPIV3StoriesStoryPublicIDTasksTaskPublicIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Task)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIV3StoriesStoryPublicIDTasksTaskPublicIDBadRequest creates a GetAPIV3StoriesStoryPublicIDTasksTaskPublicIDBadRequest with default headers values
func NewGetAPIV3StoriesStoryPublicIDTasksTaskPublicIDBadRequest() *GetAPIV3StoriesStoryPublicIDTasksTaskPublicIDBadRequest {
	return &GetAPIV3StoriesStoryPublicIDTasksTaskPublicIDBadRequest{}
}

/*GetAPIV3StoriesStoryPublicIDTasksTaskPublicIDBadRequest handles this case with default header values.

Schema mismatch
*/
type GetAPIV3StoriesStoryPublicIDTasksTaskPublicIDBadRequest struct {
}

func (o *GetAPIV3StoriesStoryPublicIDTasksTaskPublicIDBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/v3/stories/{story-public-id}/tasks/{task-public-id}][%d] getApiV3StoriesStoryPublicIdTasksTaskPublicIdBadRequest ", 400)
}

func (o *GetAPIV3StoriesStoryPublicIDTasksTaskPublicIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAPIV3StoriesStoryPublicIDTasksTaskPublicIDNotFound creates a GetAPIV3StoriesStoryPublicIDTasksTaskPublicIDNotFound with default headers values
func NewGetAPIV3StoriesStoryPublicIDTasksTaskPublicIDNotFound() *GetAPIV3StoriesStoryPublicIDTasksTaskPublicIDNotFound {
	return &GetAPIV3StoriesStoryPublicIDTasksTaskPublicIDNotFound{}
}

/*GetAPIV3StoriesStoryPublicIDTasksTaskPublicIDNotFound handles this case with default header values.

Resource does not exist
*/
type GetAPIV3StoriesStoryPublicIDTasksTaskPublicIDNotFound struct {
}

func (o *GetAPIV3StoriesStoryPublicIDTasksTaskPublicIDNotFound) Error() string {
	return fmt.Sprintf("[GET /api/v3/stories/{story-public-id}/tasks/{task-public-id}][%d] getApiV3StoriesStoryPublicIdTasksTaskPublicIdNotFound ", 404)
}

func (o *GetAPIV3StoriesStoryPublicIDTasksTaskPublicIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAPIV3StoriesStoryPublicIDTasksTaskPublicIDUnprocessableEntity creates a GetAPIV3StoriesStoryPublicIDTasksTaskPublicIDUnprocessableEntity with default headers values
func NewGetAPIV3StoriesStoryPublicIDTasksTaskPublicIDUnprocessableEntity() *GetAPIV3StoriesStoryPublicIDTasksTaskPublicIDUnprocessableEntity {
	return &GetAPIV3StoriesStoryPublicIDTasksTaskPublicIDUnprocessableEntity{}
}

/*GetAPIV3StoriesStoryPublicIDTasksTaskPublicIDUnprocessableEntity handles this case with default header values.

Unprocessable
*/
type GetAPIV3StoriesStoryPublicIDTasksTaskPublicIDUnprocessableEntity struct {
}

func (o *GetAPIV3StoriesStoryPublicIDTasksTaskPublicIDUnprocessableEntity) Error() string {
	return fmt.Sprintf("[GET /api/v3/stories/{story-public-id}/tasks/{task-public-id}][%d] getApiV3StoriesStoryPublicIdTasksTaskPublicIdUnprocessableEntity ", 422)
}

func (o *GetAPIV3StoriesStoryPublicIDTasksTaskPublicIDUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
