// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/bateau-eng/chapi/pkg/models"
)

// GetAPIV3CategoriesReader is a Reader for the GetAPIV3Categories structure.
type GetAPIV3CategoriesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV3CategoriesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIV3CategoriesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetAPIV3CategoriesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetAPIV3CategoriesNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewGetAPIV3CategoriesUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAPIV3CategoriesOK creates a GetAPIV3CategoriesOK with default headers values
func NewGetAPIV3CategoriesOK() *GetAPIV3CategoriesOK {
	return &GetAPIV3CategoriesOK{}
}

/*GetAPIV3CategoriesOK handles this case with default header values.

Resource
*/
type GetAPIV3CategoriesOK struct {
	Payload []*models.Category
}

func (o *GetAPIV3CategoriesOK) Error() string {
	return fmt.Sprintf("[GET /api/v3/categories][%d] getApiV3CategoriesOK  %+v", 200, o.Payload)
}

func (o *GetAPIV3CategoriesOK) GetPayload() []*models.Category {
	return o.Payload
}

func (o *GetAPIV3CategoriesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIV3CategoriesBadRequest creates a GetAPIV3CategoriesBadRequest with default headers values
func NewGetAPIV3CategoriesBadRequest() *GetAPIV3CategoriesBadRequest {
	return &GetAPIV3CategoriesBadRequest{}
}

/*GetAPIV3CategoriesBadRequest handles this case with default header values.

Schema mismatch
*/
type GetAPIV3CategoriesBadRequest struct {
}

func (o *GetAPIV3CategoriesBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/v3/categories][%d] getApiV3CategoriesBadRequest ", 400)
}

func (o *GetAPIV3CategoriesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAPIV3CategoriesNotFound creates a GetAPIV3CategoriesNotFound with default headers values
func NewGetAPIV3CategoriesNotFound() *GetAPIV3CategoriesNotFound {
	return &GetAPIV3CategoriesNotFound{}
}

/*GetAPIV3CategoriesNotFound handles this case with default header values.

Resource does not exist
*/
type GetAPIV3CategoriesNotFound struct {
}

func (o *GetAPIV3CategoriesNotFound) Error() string {
	return fmt.Sprintf("[GET /api/v3/categories][%d] getApiV3CategoriesNotFound ", 404)
}

func (o *GetAPIV3CategoriesNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAPIV3CategoriesUnprocessableEntity creates a GetAPIV3CategoriesUnprocessableEntity with default headers values
func NewGetAPIV3CategoriesUnprocessableEntity() *GetAPIV3CategoriesUnprocessableEntity {
	return &GetAPIV3CategoriesUnprocessableEntity{}
}

/*GetAPIV3CategoriesUnprocessableEntity handles this case with default header values.

Unprocessable
*/
type GetAPIV3CategoriesUnprocessableEntity struct {
}

func (o *GetAPIV3CategoriesUnprocessableEntity) Error() string {
	return fmt.Sprintf("[GET /api/v3/categories][%d] getApiV3CategoriesUnprocessableEntity ", 422)
}

func (o *GetAPIV3CategoriesUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
