// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAPIV3WorkflowsParams creates a new GetAPIV3WorkflowsParams object
// with the default values initialized.
func NewGetAPIV3WorkflowsParams() *GetAPIV3WorkflowsParams {

	return &GetAPIV3WorkflowsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIV3WorkflowsParamsWithTimeout creates a new GetAPIV3WorkflowsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAPIV3WorkflowsParamsWithTimeout(timeout time.Duration) *GetAPIV3WorkflowsParams {

	return &GetAPIV3WorkflowsParams{

		timeout: timeout,
	}
}

// NewGetAPIV3WorkflowsParamsWithContext creates a new GetAPIV3WorkflowsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAPIV3WorkflowsParamsWithContext(ctx context.Context) *GetAPIV3WorkflowsParams {

	return &GetAPIV3WorkflowsParams{

		Context: ctx,
	}
}

// NewGetAPIV3WorkflowsParamsWithHTTPClient creates a new GetAPIV3WorkflowsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAPIV3WorkflowsParamsWithHTTPClient(client *http.Client) *GetAPIV3WorkflowsParams {

	return &GetAPIV3WorkflowsParams{
		HTTPClient: client,
	}
}

/*GetAPIV3WorkflowsParams contains all the parameters to send to the API endpoint
for the get API v3 workflows operation typically these are written to a http.Request
*/
type GetAPIV3WorkflowsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get API v3 workflows params
func (o *GetAPIV3WorkflowsParams) WithTimeout(timeout time.Duration) *GetAPIV3WorkflowsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API v3 workflows params
func (o *GetAPIV3WorkflowsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API v3 workflows params
func (o *GetAPIV3WorkflowsParams) WithContext(ctx context.Context) *GetAPIV3WorkflowsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API v3 workflows params
func (o *GetAPIV3WorkflowsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API v3 workflows params
func (o *GetAPIV3WorkflowsParams) WithHTTPClient(client *http.Client) *GetAPIV3WorkflowsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API v3 workflows params
func (o *GetAPIV3WorkflowsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIV3WorkflowsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
