// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/bateau-eng/chapi/pkg/models"
)

// NewPostAPIV3ProjectsParams creates a new PostAPIV3ProjectsParams object
// with the default values initialized.
func NewPostAPIV3ProjectsParams() *PostAPIV3ProjectsParams {
	var ()
	return &PostAPIV3ProjectsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostAPIV3ProjectsParamsWithTimeout creates a new PostAPIV3ProjectsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostAPIV3ProjectsParamsWithTimeout(timeout time.Duration) *PostAPIV3ProjectsParams {
	var ()
	return &PostAPIV3ProjectsParams{

		timeout: timeout,
	}
}

// NewPostAPIV3ProjectsParamsWithContext creates a new PostAPIV3ProjectsParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostAPIV3ProjectsParamsWithContext(ctx context.Context) *PostAPIV3ProjectsParams {
	var ()
	return &PostAPIV3ProjectsParams{

		Context: ctx,
	}
}

// NewPostAPIV3ProjectsParamsWithHTTPClient creates a new PostAPIV3ProjectsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostAPIV3ProjectsParamsWithHTTPClient(client *http.Client) *PostAPIV3ProjectsParams {
	var ()
	return &PostAPIV3ProjectsParams{
		HTTPClient: client,
	}
}

/*PostAPIV3ProjectsParams contains all the parameters to send to the API endpoint
for the post API v3 projects operation typically these are written to a http.Request
*/
type PostAPIV3ProjectsParams struct {

	/*CreateProject*/
	CreateProject *models.CreateProject

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post API v3 projects params
func (o *PostAPIV3ProjectsParams) WithTimeout(timeout time.Duration) *PostAPIV3ProjectsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post API v3 projects params
func (o *PostAPIV3ProjectsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post API v3 projects params
func (o *PostAPIV3ProjectsParams) WithContext(ctx context.Context) *PostAPIV3ProjectsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post API v3 projects params
func (o *PostAPIV3ProjectsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post API v3 projects params
func (o *PostAPIV3ProjectsParams) WithHTTPClient(client *http.Client) *PostAPIV3ProjectsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post API v3 projects params
func (o *PostAPIV3ProjectsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCreateProject adds the createProject to the post API v3 projects params
func (o *PostAPIV3ProjectsParams) WithCreateProject(createProject *models.CreateProject) *PostAPIV3ProjectsParams {
	o.SetCreateProject(createProject)
	return o
}

// SetCreateProject adds the createProject to the post API v3 projects params
func (o *PostAPIV3ProjectsParams) SetCreateProject(createProject *models.CreateProject) {
	o.CreateProject = createProject
}

// WriteToRequest writes these params to a swagger request
func (o *PostAPIV3ProjectsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.CreateProject != nil {
		if err := r.SetBodyParam(o.CreateProject); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
