// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/bateau-eng/chapi/v0/pkg/models"
)

// PostAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactionsReader is a Reader for the PostAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactions structure.
type PostAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPostAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactionsCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactionsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPostAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactionsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewPostAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactionsUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactionsCreated creates a PostAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactionsCreated with default headers values
func NewPostAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactionsCreated() *PostAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactionsCreated {
	return &PostAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactionsCreated{}
}

/*PostAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactionsCreated handles this case with default header values.

Resource
*/
type PostAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactionsCreated struct {
	Payload []*models.Reaction
}

func (o *PostAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactionsCreated) Error() string {
	return fmt.Sprintf("[POST /api/v3/stories/{story-public-id}/comments/{comment-public-id}/reactions][%d] postApiV3StoriesStoryPublicIdCommentsCommentPublicIdReactionsCreated  %+v", 201, o.Payload)
}

func (o *PostAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactionsCreated) GetPayload() []*models.Reaction {
	return o.Payload
}

func (o *PostAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactionsCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactionsBadRequest creates a PostAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactionsBadRequest with default headers values
func NewPostAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactionsBadRequest() *PostAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactionsBadRequest {
	return &PostAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactionsBadRequest{}
}

/*PostAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactionsBadRequest handles this case with default header values.

Schema mismatch
*/
type PostAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactionsBadRequest struct {
}

func (o *PostAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactionsBadRequest) Error() string {
	return fmt.Sprintf("[POST /api/v3/stories/{story-public-id}/comments/{comment-public-id}/reactions][%d] postApiV3StoriesStoryPublicIdCommentsCommentPublicIdReactionsBadRequest ", 400)
}

func (o *PostAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactionsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactionsNotFound creates a PostAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactionsNotFound with default headers values
func NewPostAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactionsNotFound() *PostAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactionsNotFound {
	return &PostAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactionsNotFound{}
}

/*PostAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactionsNotFound handles this case with default header values.

Resource does not exist
*/
type PostAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactionsNotFound struct {
}

func (o *PostAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactionsNotFound) Error() string {
	return fmt.Sprintf("[POST /api/v3/stories/{story-public-id}/comments/{comment-public-id}/reactions][%d] postApiV3StoriesStoryPublicIdCommentsCommentPublicIdReactionsNotFound ", 404)
}

func (o *PostAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactionsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactionsUnprocessableEntity creates a PostAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactionsUnprocessableEntity with default headers values
func NewPostAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactionsUnprocessableEntity() *PostAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactionsUnprocessableEntity {
	return &PostAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactionsUnprocessableEntity{}
}

/*PostAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactionsUnprocessableEntity handles this case with default header values.

Unprocessable
*/
type PostAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactionsUnprocessableEntity struct {
}

func (o *PostAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactionsUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /api/v3/stories/{story-public-id}/comments/{comment-public-id}/reactions][%d] postApiV3StoriesStoryPublicIdCommentsCommentPublicIdReactionsUnprocessableEntity ", 422)
}

func (o *PostAPIV3StoriesStoryPublicIDCommentsCommentPublicIDReactionsUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
