// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/bateau-eng/chapi/pkg/models"
)

// PostAPIV3FilesReader is a Reader for the PostAPIV3Files structure.
type PostAPIV3FilesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAPIV3FilesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPostAPIV3FilesCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostAPIV3FilesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPostAPIV3FilesNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewPostAPIV3FilesUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostAPIV3FilesCreated creates a PostAPIV3FilesCreated with default headers values
func NewPostAPIV3FilesCreated() *PostAPIV3FilesCreated {
	return &PostAPIV3FilesCreated{}
}

/*PostAPIV3FilesCreated handles this case with default header values.

Resource
*/
type PostAPIV3FilesCreated struct {
	Payload []*models.File
}

func (o *PostAPIV3FilesCreated) Error() string {
	return fmt.Sprintf("[POST /api/v3/files][%d] postApiV3FilesCreated  %+v", 201, o.Payload)
}

func (o *PostAPIV3FilesCreated) GetPayload() []*models.File {
	return o.Payload
}

func (o *PostAPIV3FilesCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAPIV3FilesBadRequest creates a PostAPIV3FilesBadRequest with default headers values
func NewPostAPIV3FilesBadRequest() *PostAPIV3FilesBadRequest {
	return &PostAPIV3FilesBadRequest{}
}

/*PostAPIV3FilesBadRequest handles this case with default header values.

Schema mismatch
*/
type PostAPIV3FilesBadRequest struct {
}

func (o *PostAPIV3FilesBadRequest) Error() string {
	return fmt.Sprintf("[POST /api/v3/files][%d] postApiV3FilesBadRequest ", 400)
}

func (o *PostAPIV3FilesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostAPIV3FilesNotFound creates a PostAPIV3FilesNotFound with default headers values
func NewPostAPIV3FilesNotFound() *PostAPIV3FilesNotFound {
	return &PostAPIV3FilesNotFound{}
}

/*PostAPIV3FilesNotFound handles this case with default header values.

Resource does not exist
*/
type PostAPIV3FilesNotFound struct {
}

func (o *PostAPIV3FilesNotFound) Error() string {
	return fmt.Sprintf("[POST /api/v3/files][%d] postApiV3FilesNotFound ", 404)
}

func (o *PostAPIV3FilesNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostAPIV3FilesUnprocessableEntity creates a PostAPIV3FilesUnprocessableEntity with default headers values
func NewPostAPIV3FilesUnprocessableEntity() *PostAPIV3FilesUnprocessableEntity {
	return &PostAPIV3FilesUnprocessableEntity{}
}

/*PostAPIV3FilesUnprocessableEntity handles this case with default header values.

Unprocessable
*/
type PostAPIV3FilesUnprocessableEntity struct {
}

func (o *PostAPIV3FilesUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /api/v3/files][%d] postApiV3FilesUnprocessableEntity ", 422)
}

func (o *PostAPIV3FilesUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
