// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/bateau-eng/chapi/v0/pkg/models"
)

// PostAPIV3EpicsReader is a Reader for the PostAPIV3Epics structure.
type PostAPIV3EpicsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAPIV3EpicsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPostAPIV3EpicsCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostAPIV3EpicsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPostAPIV3EpicsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewPostAPIV3EpicsUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostAPIV3EpicsCreated creates a PostAPIV3EpicsCreated with default headers values
func NewPostAPIV3EpicsCreated() *PostAPIV3EpicsCreated {
	return &PostAPIV3EpicsCreated{}
}

/*PostAPIV3EpicsCreated handles this case with default header values.

Resource
*/
type PostAPIV3EpicsCreated struct {
	Payload *models.Epic
}

func (o *PostAPIV3EpicsCreated) Error() string {
	return fmt.Sprintf("[POST /api/v3/epics][%d] postApiV3EpicsCreated  %+v", 201, o.Payload)
}

func (o *PostAPIV3EpicsCreated) GetPayload() *models.Epic {
	return o.Payload
}

func (o *PostAPIV3EpicsCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Epic)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAPIV3EpicsBadRequest creates a PostAPIV3EpicsBadRequest with default headers values
func NewPostAPIV3EpicsBadRequest() *PostAPIV3EpicsBadRequest {
	return &PostAPIV3EpicsBadRequest{}
}

/*PostAPIV3EpicsBadRequest handles this case with default header values.

Schema mismatch
*/
type PostAPIV3EpicsBadRequest struct {
}

func (o *PostAPIV3EpicsBadRequest) Error() string {
	return fmt.Sprintf("[POST /api/v3/epics][%d] postApiV3EpicsBadRequest ", 400)
}

func (o *PostAPIV3EpicsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostAPIV3EpicsNotFound creates a PostAPIV3EpicsNotFound with default headers values
func NewPostAPIV3EpicsNotFound() *PostAPIV3EpicsNotFound {
	return &PostAPIV3EpicsNotFound{}
}

/*PostAPIV3EpicsNotFound handles this case with default header values.

Resource does not exist
*/
type PostAPIV3EpicsNotFound struct {
}

func (o *PostAPIV3EpicsNotFound) Error() string {
	return fmt.Sprintf("[POST /api/v3/epics][%d] postApiV3EpicsNotFound ", 404)
}

func (o *PostAPIV3EpicsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostAPIV3EpicsUnprocessableEntity creates a PostAPIV3EpicsUnprocessableEntity with default headers values
func NewPostAPIV3EpicsUnprocessableEntity() *PostAPIV3EpicsUnprocessableEntity {
	return &PostAPIV3EpicsUnprocessableEntity{}
}

/*PostAPIV3EpicsUnprocessableEntity handles this case with default header values.

Unprocessable
*/
type PostAPIV3EpicsUnprocessableEntity struct {
}

func (o *PostAPIV3EpicsUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /api/v3/epics][%d] postApiV3EpicsUnprocessableEntity ", 422)
}

func (o *PostAPIV3EpicsUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
