// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/bateau-eng/chapi/v0/pkg/models"
)

// PostAPIV3StoryLinksReader is a Reader for the PostAPIV3StoryLinks structure.
type PostAPIV3StoryLinksReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAPIV3StoryLinksReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPostAPIV3StoryLinksCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostAPIV3StoryLinksBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPostAPIV3StoryLinksNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewPostAPIV3StoryLinksUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostAPIV3StoryLinksCreated creates a PostAPIV3StoryLinksCreated with default headers values
func NewPostAPIV3StoryLinksCreated() *PostAPIV3StoryLinksCreated {
	return &PostAPIV3StoryLinksCreated{}
}

/*PostAPIV3StoryLinksCreated handles this case with default header values.

Resource
*/
type PostAPIV3StoryLinksCreated struct {
	Payload *models.StoryLink
}

func (o *PostAPIV3StoryLinksCreated) Error() string {
	return fmt.Sprintf("[POST /api/v3/story-links][%d] postApiV3StoryLinksCreated  %+v", 201, o.Payload)
}

func (o *PostAPIV3StoryLinksCreated) GetPayload() *models.StoryLink {
	return o.Payload
}

func (o *PostAPIV3StoryLinksCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StoryLink)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAPIV3StoryLinksBadRequest creates a PostAPIV3StoryLinksBadRequest with default headers values
func NewPostAPIV3StoryLinksBadRequest() *PostAPIV3StoryLinksBadRequest {
	return &PostAPIV3StoryLinksBadRequest{}
}

/*PostAPIV3StoryLinksBadRequest handles this case with default header values.

Schema mismatch
*/
type PostAPIV3StoryLinksBadRequest struct {
}

func (o *PostAPIV3StoryLinksBadRequest) Error() string {
	return fmt.Sprintf("[POST /api/v3/story-links][%d] postApiV3StoryLinksBadRequest ", 400)
}

func (o *PostAPIV3StoryLinksBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostAPIV3StoryLinksNotFound creates a PostAPIV3StoryLinksNotFound with default headers values
func NewPostAPIV3StoryLinksNotFound() *PostAPIV3StoryLinksNotFound {
	return &PostAPIV3StoryLinksNotFound{}
}

/*PostAPIV3StoryLinksNotFound handles this case with default header values.

Resource does not exist
*/
type PostAPIV3StoryLinksNotFound struct {
}

func (o *PostAPIV3StoryLinksNotFound) Error() string {
	return fmt.Sprintf("[POST /api/v3/story-links][%d] postApiV3StoryLinksNotFound ", 404)
}

func (o *PostAPIV3StoryLinksNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostAPIV3StoryLinksUnprocessableEntity creates a PostAPIV3StoryLinksUnprocessableEntity with default headers values
func NewPostAPIV3StoryLinksUnprocessableEntity() *PostAPIV3StoryLinksUnprocessableEntity {
	return &PostAPIV3StoryLinksUnprocessableEntity{}
}

/*PostAPIV3StoryLinksUnprocessableEntity handles this case with default header values.

Unprocessable
*/
type PostAPIV3StoryLinksUnprocessableEntity struct {
}

func (o *PostAPIV3StoryLinksUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /api/v3/story-links][%d] postApiV3StoryLinksUnprocessableEntity ", 422)
}

func (o *PostAPIV3StoryLinksUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
