// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/bateau-eng/chapi/pkg/models"
)

// PostAPIV3StoriesStoryPublicIDTasksReader is a Reader for the PostAPIV3StoriesStoryPublicIDTasks structure.
type PostAPIV3StoriesStoryPublicIDTasksReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAPIV3StoriesStoryPublicIDTasksReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPostAPIV3StoriesStoryPublicIDTasksCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostAPIV3StoriesStoryPublicIDTasksBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPostAPIV3StoriesStoryPublicIDTasksNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewPostAPIV3StoriesStoryPublicIDTasksUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostAPIV3StoriesStoryPublicIDTasksCreated creates a PostAPIV3StoriesStoryPublicIDTasksCreated with default headers values
func NewPostAPIV3StoriesStoryPublicIDTasksCreated() *PostAPIV3StoriesStoryPublicIDTasksCreated {
	return &PostAPIV3StoriesStoryPublicIDTasksCreated{}
}

/*PostAPIV3StoriesStoryPublicIDTasksCreated handles this case with default header values.

Resource
*/
type PostAPIV3StoriesStoryPublicIDTasksCreated struct {
	Payload *models.Task
}

func (o *PostAPIV3StoriesStoryPublicIDTasksCreated) Error() string {
	return fmt.Sprintf("[POST /api/v3/stories/{story-public-id}/tasks][%d] postApiV3StoriesStoryPublicIdTasksCreated  %+v", 201, o.Payload)
}

func (o *PostAPIV3StoriesStoryPublicIDTasksCreated) GetPayload() *models.Task {
	return o.Payload
}

func (o *PostAPIV3StoriesStoryPublicIDTasksCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Task)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAPIV3StoriesStoryPublicIDTasksBadRequest creates a PostAPIV3StoriesStoryPublicIDTasksBadRequest with default headers values
func NewPostAPIV3StoriesStoryPublicIDTasksBadRequest() *PostAPIV3StoriesStoryPublicIDTasksBadRequest {
	return &PostAPIV3StoriesStoryPublicIDTasksBadRequest{}
}

/*PostAPIV3StoriesStoryPublicIDTasksBadRequest handles this case with default header values.

Schema mismatch
*/
type PostAPIV3StoriesStoryPublicIDTasksBadRequest struct {
}

func (o *PostAPIV3StoriesStoryPublicIDTasksBadRequest) Error() string {
	return fmt.Sprintf("[POST /api/v3/stories/{story-public-id}/tasks][%d] postApiV3StoriesStoryPublicIdTasksBadRequest ", 400)
}

func (o *PostAPIV3StoriesStoryPublicIDTasksBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostAPIV3StoriesStoryPublicIDTasksNotFound creates a PostAPIV3StoriesStoryPublicIDTasksNotFound with default headers values
func NewPostAPIV3StoriesStoryPublicIDTasksNotFound() *PostAPIV3StoriesStoryPublicIDTasksNotFound {
	return &PostAPIV3StoriesStoryPublicIDTasksNotFound{}
}

/*PostAPIV3StoriesStoryPublicIDTasksNotFound handles this case with default header values.

Resource does not exist
*/
type PostAPIV3StoriesStoryPublicIDTasksNotFound struct {
}

func (o *PostAPIV3StoriesStoryPublicIDTasksNotFound) Error() string {
	return fmt.Sprintf("[POST /api/v3/stories/{story-public-id}/tasks][%d] postApiV3StoriesStoryPublicIdTasksNotFound ", 404)
}

func (o *PostAPIV3StoriesStoryPublicIDTasksNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostAPIV3StoriesStoryPublicIDTasksUnprocessableEntity creates a PostAPIV3StoriesStoryPublicIDTasksUnprocessableEntity with default headers values
func NewPostAPIV3StoriesStoryPublicIDTasksUnprocessableEntity() *PostAPIV3StoriesStoryPublicIDTasksUnprocessableEntity {
	return &PostAPIV3StoriesStoryPublicIDTasksUnprocessableEntity{}
}

/*PostAPIV3StoriesStoryPublicIDTasksUnprocessableEntity handles this case with default header values.

Unprocessable
*/
type PostAPIV3StoriesStoryPublicIDTasksUnprocessableEntity struct {
}

func (o *PostAPIV3StoriesStoryPublicIDTasksUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /api/v3/stories/{story-public-id}/tasks][%d] postApiV3StoriesStoryPublicIdTasksUnprocessableEntity ", 422)
}

func (o *PostAPIV3StoriesStoryPublicIDTasksUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
