// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/bateau-eng/chapi/v0/pkg/models"
)

// PostAPIV3GroupsReader is a Reader for the PostAPIV3Groups structure.
type PostAPIV3GroupsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAPIV3GroupsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPostAPIV3GroupsCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostAPIV3GroupsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPostAPIV3GroupsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewPostAPIV3GroupsUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostAPIV3GroupsCreated creates a PostAPIV3GroupsCreated with default headers values
func NewPostAPIV3GroupsCreated() *PostAPIV3GroupsCreated {
	return &PostAPIV3GroupsCreated{}
}

/*PostAPIV3GroupsCreated handles this case with default header values.

Resource
*/
type PostAPIV3GroupsCreated struct {
	Payload *models.Group
}

func (o *PostAPIV3GroupsCreated) Error() string {
	return fmt.Sprintf("[POST /api/v3/groups][%d] postApiV3GroupsCreated  %+v", 201, o.Payload)
}

func (o *PostAPIV3GroupsCreated) GetPayload() *models.Group {
	return o.Payload
}

func (o *PostAPIV3GroupsCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Group)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAPIV3GroupsBadRequest creates a PostAPIV3GroupsBadRequest with default headers values
func NewPostAPIV3GroupsBadRequest() *PostAPIV3GroupsBadRequest {
	return &PostAPIV3GroupsBadRequest{}
}

/*PostAPIV3GroupsBadRequest handles this case with default header values.

Schema mismatch
*/
type PostAPIV3GroupsBadRequest struct {
}

func (o *PostAPIV3GroupsBadRequest) Error() string {
	return fmt.Sprintf("[POST /api/v3/groups][%d] postApiV3GroupsBadRequest ", 400)
}

func (o *PostAPIV3GroupsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostAPIV3GroupsNotFound creates a PostAPIV3GroupsNotFound with default headers values
func NewPostAPIV3GroupsNotFound() *PostAPIV3GroupsNotFound {
	return &PostAPIV3GroupsNotFound{}
}

/*PostAPIV3GroupsNotFound handles this case with default header values.

Resource does not exist
*/
type PostAPIV3GroupsNotFound struct {
}

func (o *PostAPIV3GroupsNotFound) Error() string {
	return fmt.Sprintf("[POST /api/v3/groups][%d] postApiV3GroupsNotFound ", 404)
}

func (o *PostAPIV3GroupsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostAPIV3GroupsUnprocessableEntity creates a PostAPIV3GroupsUnprocessableEntity with default headers values
func NewPostAPIV3GroupsUnprocessableEntity() *PostAPIV3GroupsUnprocessableEntity {
	return &PostAPIV3GroupsUnprocessableEntity{}
}

/*PostAPIV3GroupsUnprocessableEntity handles this case with default header values.

Unprocessable
*/
type PostAPIV3GroupsUnprocessableEntity struct {
}

func (o *PostAPIV3GroupsUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /api/v3/groups][%d] postApiV3GroupsUnprocessableEntity ", 422)
}

func (o *PostAPIV3GroupsUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
