// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/bateau-eng/chapi/v0/pkg/models"
)

// NewPostAPIV3StoriesBulkParams creates a new PostAPIV3StoriesBulkParams object
// with the default values initialized.
func NewPostAPIV3StoriesBulkParams() *PostAPIV3StoriesBulkParams {
	var ()
	return &PostAPIV3StoriesBulkParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostAPIV3StoriesBulkParamsWithTimeout creates a new PostAPIV3StoriesBulkParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostAPIV3StoriesBulkParamsWithTimeout(timeout time.Duration) *PostAPIV3StoriesBulkParams {
	var ()
	return &PostAPIV3StoriesBulkParams{

		timeout: timeout,
	}
}

// NewPostAPIV3StoriesBulkParamsWithContext creates a new PostAPIV3StoriesBulkParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostAPIV3StoriesBulkParamsWithContext(ctx context.Context) *PostAPIV3StoriesBulkParams {
	var ()
	return &PostAPIV3StoriesBulkParams{

		Context: ctx,
	}
}

// NewPostAPIV3StoriesBulkParamsWithHTTPClient creates a new PostAPIV3StoriesBulkParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostAPIV3StoriesBulkParamsWithHTTPClient(client *http.Client) *PostAPIV3StoriesBulkParams {
	var ()
	return &PostAPIV3StoriesBulkParams{
		HTTPClient: client,
	}
}

/*PostAPIV3StoriesBulkParams contains all the parameters to send to the API endpoint
for the post API v3 stories bulk operation typically these are written to a http.Request
*/
type PostAPIV3StoriesBulkParams struct {

	/*CreateStories*/
	CreateStories *models.CreateStories

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post API v3 stories bulk params
func (o *PostAPIV3StoriesBulkParams) WithTimeout(timeout time.Duration) *PostAPIV3StoriesBulkParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post API v3 stories bulk params
func (o *PostAPIV3StoriesBulkParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post API v3 stories bulk params
func (o *PostAPIV3StoriesBulkParams) WithContext(ctx context.Context) *PostAPIV3StoriesBulkParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post API v3 stories bulk params
func (o *PostAPIV3StoriesBulkParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post API v3 stories bulk params
func (o *PostAPIV3StoriesBulkParams) WithHTTPClient(client *http.Client) *PostAPIV3StoriesBulkParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post API v3 stories bulk params
func (o *PostAPIV3StoriesBulkParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCreateStories adds the createStories to the post API v3 stories bulk params
func (o *PostAPIV3StoriesBulkParams) WithCreateStories(createStories *models.CreateStories) *PostAPIV3StoriesBulkParams {
	o.SetCreateStories(createStories)
	return o
}

// SetCreateStories adds the createStories to the post API v3 stories bulk params
func (o *PostAPIV3StoriesBulkParams) SetCreateStories(createStories *models.CreateStories) {
	o.CreateStories = createStories
}

// WriteToRequest writes these params to a swagger request
func (o *PostAPIV3StoriesBulkParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.CreateStories != nil {
		if err := r.SetBodyParam(o.CreateStories); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
