// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/bateau-eng/chapi/v0/pkg/models"
)

// PostAPIV3LinkedFilesReader is a Reader for the PostAPIV3LinkedFiles structure.
type PostAPIV3LinkedFilesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAPIV3LinkedFilesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPostAPIV3LinkedFilesCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostAPIV3LinkedFilesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPostAPIV3LinkedFilesNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewPostAPIV3LinkedFilesUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostAPIV3LinkedFilesCreated creates a PostAPIV3LinkedFilesCreated with default headers values
func NewPostAPIV3LinkedFilesCreated() *PostAPIV3LinkedFilesCreated {
	return &PostAPIV3LinkedFilesCreated{}
}

/*PostAPIV3LinkedFilesCreated handles this case with default header values.

Resource
*/
type PostAPIV3LinkedFilesCreated struct {
	Payload *models.LinkedFile
}

func (o *PostAPIV3LinkedFilesCreated) Error() string {
	return fmt.Sprintf("[POST /api/v3/linked-files][%d] postApiV3LinkedFilesCreated  %+v", 201, o.Payload)
}

func (o *PostAPIV3LinkedFilesCreated) GetPayload() *models.LinkedFile {
	return o.Payload
}

func (o *PostAPIV3LinkedFilesCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.LinkedFile)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAPIV3LinkedFilesBadRequest creates a PostAPIV3LinkedFilesBadRequest with default headers values
func NewPostAPIV3LinkedFilesBadRequest() *PostAPIV3LinkedFilesBadRequest {
	return &PostAPIV3LinkedFilesBadRequest{}
}

/*PostAPIV3LinkedFilesBadRequest handles this case with default header values.

Schema mismatch
*/
type PostAPIV3LinkedFilesBadRequest struct {
}

func (o *PostAPIV3LinkedFilesBadRequest) Error() string {
	return fmt.Sprintf("[POST /api/v3/linked-files][%d] postApiV3LinkedFilesBadRequest ", 400)
}

func (o *PostAPIV3LinkedFilesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostAPIV3LinkedFilesNotFound creates a PostAPIV3LinkedFilesNotFound with default headers values
func NewPostAPIV3LinkedFilesNotFound() *PostAPIV3LinkedFilesNotFound {
	return &PostAPIV3LinkedFilesNotFound{}
}

/*PostAPIV3LinkedFilesNotFound handles this case with default header values.

Resource does not exist
*/
type PostAPIV3LinkedFilesNotFound struct {
}

func (o *PostAPIV3LinkedFilesNotFound) Error() string {
	return fmt.Sprintf("[POST /api/v3/linked-files][%d] postApiV3LinkedFilesNotFound ", 404)
}

func (o *PostAPIV3LinkedFilesNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostAPIV3LinkedFilesUnprocessableEntity creates a PostAPIV3LinkedFilesUnprocessableEntity with default headers values
func NewPostAPIV3LinkedFilesUnprocessableEntity() *PostAPIV3LinkedFilesUnprocessableEntity {
	return &PostAPIV3LinkedFilesUnprocessableEntity{}
}

/*PostAPIV3LinkedFilesUnprocessableEntity handles this case with default header values.

Unprocessable
*/
type PostAPIV3LinkedFilesUnprocessableEntity struct {
}

func (o *PostAPIV3LinkedFilesUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /api/v3/linked-files][%d] postApiV3LinkedFilesUnprocessableEntity ", 422)
}

func (o *PostAPIV3LinkedFilesUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
