// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/bateau-eng/chapi/v0/pkg/models"
)

// PutAPIV3CategoriesCategoryPublicIDReader is a Reader for the PutAPIV3CategoriesCategoryPublicID structure.
type PutAPIV3CategoriesCategoryPublicIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutAPIV3CategoriesCategoryPublicIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPutAPIV3CategoriesCategoryPublicIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPutAPIV3CategoriesCategoryPublicIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPutAPIV3CategoriesCategoryPublicIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewPutAPIV3CategoriesCategoryPublicIDUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPutAPIV3CategoriesCategoryPublicIDOK creates a PutAPIV3CategoriesCategoryPublicIDOK with default headers values
func NewPutAPIV3CategoriesCategoryPublicIDOK() *PutAPIV3CategoriesCategoryPublicIDOK {
	return &PutAPIV3CategoriesCategoryPublicIDOK{}
}

/*PutAPIV3CategoriesCategoryPublicIDOK handles this case with default header values.

Resource
*/
type PutAPIV3CategoriesCategoryPublicIDOK struct {
	Payload *models.Category
}

func (o *PutAPIV3CategoriesCategoryPublicIDOK) Error() string {
	return fmt.Sprintf("[PUT /api/v3/categories/{category-public-id}][%d] putApiV3CategoriesCategoryPublicIdOK  %+v", 200, o.Payload)
}

func (o *PutAPIV3CategoriesCategoryPublicIDOK) GetPayload() *models.Category {
	return o.Payload
}

func (o *PutAPIV3CategoriesCategoryPublicIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Category)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutAPIV3CategoriesCategoryPublicIDBadRequest creates a PutAPIV3CategoriesCategoryPublicIDBadRequest with default headers values
func NewPutAPIV3CategoriesCategoryPublicIDBadRequest() *PutAPIV3CategoriesCategoryPublicIDBadRequest {
	return &PutAPIV3CategoriesCategoryPublicIDBadRequest{}
}

/*PutAPIV3CategoriesCategoryPublicIDBadRequest handles this case with default header values.

Schema mismatch
*/
type PutAPIV3CategoriesCategoryPublicIDBadRequest struct {
}

func (o *PutAPIV3CategoriesCategoryPublicIDBadRequest) Error() string {
	return fmt.Sprintf("[PUT /api/v3/categories/{category-public-id}][%d] putApiV3CategoriesCategoryPublicIdBadRequest ", 400)
}

func (o *PutAPIV3CategoriesCategoryPublicIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPutAPIV3CategoriesCategoryPublicIDNotFound creates a PutAPIV3CategoriesCategoryPublicIDNotFound with default headers values
func NewPutAPIV3CategoriesCategoryPublicIDNotFound() *PutAPIV3CategoriesCategoryPublicIDNotFound {
	return &PutAPIV3CategoriesCategoryPublicIDNotFound{}
}

/*PutAPIV3CategoriesCategoryPublicIDNotFound handles this case with default header values.

Resource does not exist
*/
type PutAPIV3CategoriesCategoryPublicIDNotFound struct {
}

func (o *PutAPIV3CategoriesCategoryPublicIDNotFound) Error() string {
	return fmt.Sprintf("[PUT /api/v3/categories/{category-public-id}][%d] putApiV3CategoriesCategoryPublicIdNotFound ", 404)
}

func (o *PutAPIV3CategoriesCategoryPublicIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPutAPIV3CategoriesCategoryPublicIDUnprocessableEntity creates a PutAPIV3CategoriesCategoryPublicIDUnprocessableEntity with default headers values
func NewPutAPIV3CategoriesCategoryPublicIDUnprocessableEntity() *PutAPIV3CategoriesCategoryPublicIDUnprocessableEntity {
	return &PutAPIV3CategoriesCategoryPublicIDUnprocessableEntity{}
}

/*PutAPIV3CategoriesCategoryPublicIDUnprocessableEntity handles this case with default header values.

Unprocessable
*/
type PutAPIV3CategoriesCategoryPublicIDUnprocessableEntity struct {
}

func (o *PutAPIV3CategoriesCategoryPublicIDUnprocessableEntity) Error() string {
	return fmt.Sprintf("[PUT /api/v3/categories/{category-public-id}][%d] putApiV3CategoriesCategoryPublicIdUnprocessableEntity ", 422)
}

func (o *PutAPIV3CategoriesCategoryPublicIDUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
