// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/bateau-eng/chapi/pkg/models"
)

// PutAPIV3EpicsEpicPublicIDReader is a Reader for the PutAPIV3EpicsEpicPublicID structure.
type PutAPIV3EpicsEpicPublicIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutAPIV3EpicsEpicPublicIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPutAPIV3EpicsEpicPublicIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPutAPIV3EpicsEpicPublicIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPutAPIV3EpicsEpicPublicIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewPutAPIV3EpicsEpicPublicIDUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPutAPIV3EpicsEpicPublicIDOK creates a PutAPIV3EpicsEpicPublicIDOK with default headers values
func NewPutAPIV3EpicsEpicPublicIDOK() *PutAPIV3EpicsEpicPublicIDOK {
	return &PutAPIV3EpicsEpicPublicIDOK{}
}

/*PutAPIV3EpicsEpicPublicIDOK handles this case with default header values.

Resource
*/
type PutAPIV3EpicsEpicPublicIDOK struct {
	Payload *models.Epic
}

func (o *PutAPIV3EpicsEpicPublicIDOK) Error() string {
	return fmt.Sprintf("[PUT /api/v3/epics/{epic-public-id}][%d] putApiV3EpicsEpicPublicIdOK  %+v", 200, o.Payload)
}

func (o *PutAPIV3EpicsEpicPublicIDOK) GetPayload() *models.Epic {
	return o.Payload
}

func (o *PutAPIV3EpicsEpicPublicIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Epic)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutAPIV3EpicsEpicPublicIDBadRequest creates a PutAPIV3EpicsEpicPublicIDBadRequest with default headers values
func NewPutAPIV3EpicsEpicPublicIDBadRequest() *PutAPIV3EpicsEpicPublicIDBadRequest {
	return &PutAPIV3EpicsEpicPublicIDBadRequest{}
}

/*PutAPIV3EpicsEpicPublicIDBadRequest handles this case with default header values.

Schema mismatch
*/
type PutAPIV3EpicsEpicPublicIDBadRequest struct {
}

func (o *PutAPIV3EpicsEpicPublicIDBadRequest) Error() string {
	return fmt.Sprintf("[PUT /api/v3/epics/{epic-public-id}][%d] putApiV3EpicsEpicPublicIdBadRequest ", 400)
}

func (o *PutAPIV3EpicsEpicPublicIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPutAPIV3EpicsEpicPublicIDNotFound creates a PutAPIV3EpicsEpicPublicIDNotFound with default headers values
func NewPutAPIV3EpicsEpicPublicIDNotFound() *PutAPIV3EpicsEpicPublicIDNotFound {
	return &PutAPIV3EpicsEpicPublicIDNotFound{}
}

/*PutAPIV3EpicsEpicPublicIDNotFound handles this case with default header values.

Resource does not exist
*/
type PutAPIV3EpicsEpicPublicIDNotFound struct {
}

func (o *PutAPIV3EpicsEpicPublicIDNotFound) Error() string {
	return fmt.Sprintf("[PUT /api/v3/epics/{epic-public-id}][%d] putApiV3EpicsEpicPublicIdNotFound ", 404)
}

func (o *PutAPIV3EpicsEpicPublicIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPutAPIV3EpicsEpicPublicIDUnprocessableEntity creates a PutAPIV3EpicsEpicPublicIDUnprocessableEntity with default headers values
func NewPutAPIV3EpicsEpicPublicIDUnprocessableEntity() *PutAPIV3EpicsEpicPublicIDUnprocessableEntity {
	return &PutAPIV3EpicsEpicPublicIDUnprocessableEntity{}
}

/*PutAPIV3EpicsEpicPublicIDUnprocessableEntity handles this case with default header values.

Unprocessable
*/
type PutAPIV3EpicsEpicPublicIDUnprocessableEntity struct {
}

func (o *PutAPIV3EpicsEpicPublicIDUnprocessableEntity) Error() string {
	return fmt.Sprintf("[PUT /api/v3/epics/{epic-public-id}][%d] putApiV3EpicsEpicPublicIdUnprocessableEntity ", 422)
}

func (o *PutAPIV3EpicsEpicPublicIDUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
