// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/bateau-eng/chapi/pkg/models"
)

// PutAPIV3LinkedFilesLinkedFilePublicIDReader is a Reader for the PutAPIV3LinkedFilesLinkedFilePublicID structure.
type PutAPIV3LinkedFilesLinkedFilePublicIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutAPIV3LinkedFilesLinkedFilePublicIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPutAPIV3LinkedFilesLinkedFilePublicIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPutAPIV3LinkedFilesLinkedFilePublicIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPutAPIV3LinkedFilesLinkedFilePublicIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewPutAPIV3LinkedFilesLinkedFilePublicIDUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPutAPIV3LinkedFilesLinkedFilePublicIDOK creates a PutAPIV3LinkedFilesLinkedFilePublicIDOK with default headers values
func NewPutAPIV3LinkedFilesLinkedFilePublicIDOK() *PutAPIV3LinkedFilesLinkedFilePublicIDOK {
	return &PutAPIV3LinkedFilesLinkedFilePublicIDOK{}
}

/*PutAPIV3LinkedFilesLinkedFilePublicIDOK handles this case with default header values.

Resource
*/
type PutAPIV3LinkedFilesLinkedFilePublicIDOK struct {
	Payload *models.LinkedFile
}

func (o *PutAPIV3LinkedFilesLinkedFilePublicIDOK) Error() string {
	return fmt.Sprintf("[PUT /api/v3/linked-files/{linked-file-public-id}][%d] putApiV3LinkedFilesLinkedFilePublicIdOK  %+v", 200, o.Payload)
}

func (o *PutAPIV3LinkedFilesLinkedFilePublicIDOK) GetPayload() *models.LinkedFile {
	return o.Payload
}

func (o *PutAPIV3LinkedFilesLinkedFilePublicIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.LinkedFile)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutAPIV3LinkedFilesLinkedFilePublicIDBadRequest creates a PutAPIV3LinkedFilesLinkedFilePublicIDBadRequest with default headers values
func NewPutAPIV3LinkedFilesLinkedFilePublicIDBadRequest() *PutAPIV3LinkedFilesLinkedFilePublicIDBadRequest {
	return &PutAPIV3LinkedFilesLinkedFilePublicIDBadRequest{}
}

/*PutAPIV3LinkedFilesLinkedFilePublicIDBadRequest handles this case with default header values.

Schema mismatch
*/
type PutAPIV3LinkedFilesLinkedFilePublicIDBadRequest struct {
}

func (o *PutAPIV3LinkedFilesLinkedFilePublicIDBadRequest) Error() string {
	return fmt.Sprintf("[PUT /api/v3/linked-files/{linked-file-public-id}][%d] putApiV3LinkedFilesLinkedFilePublicIdBadRequest ", 400)
}

func (o *PutAPIV3LinkedFilesLinkedFilePublicIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPutAPIV3LinkedFilesLinkedFilePublicIDNotFound creates a PutAPIV3LinkedFilesLinkedFilePublicIDNotFound with default headers values
func NewPutAPIV3LinkedFilesLinkedFilePublicIDNotFound() *PutAPIV3LinkedFilesLinkedFilePublicIDNotFound {
	return &PutAPIV3LinkedFilesLinkedFilePublicIDNotFound{}
}

/*PutAPIV3LinkedFilesLinkedFilePublicIDNotFound handles this case with default header values.

Resource does not exist
*/
type PutAPIV3LinkedFilesLinkedFilePublicIDNotFound struct {
}

func (o *PutAPIV3LinkedFilesLinkedFilePublicIDNotFound) Error() string {
	return fmt.Sprintf("[PUT /api/v3/linked-files/{linked-file-public-id}][%d] putApiV3LinkedFilesLinkedFilePublicIdNotFound ", 404)
}

func (o *PutAPIV3LinkedFilesLinkedFilePublicIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPutAPIV3LinkedFilesLinkedFilePublicIDUnprocessableEntity creates a PutAPIV3LinkedFilesLinkedFilePublicIDUnprocessableEntity with default headers values
func NewPutAPIV3LinkedFilesLinkedFilePublicIDUnprocessableEntity() *PutAPIV3LinkedFilesLinkedFilePublicIDUnprocessableEntity {
	return &PutAPIV3LinkedFilesLinkedFilePublicIDUnprocessableEntity{}
}

/*PutAPIV3LinkedFilesLinkedFilePublicIDUnprocessableEntity handles this case with default header values.

Unprocessable
*/
type PutAPIV3LinkedFilesLinkedFilePublicIDUnprocessableEntity struct {
}

func (o *PutAPIV3LinkedFilesLinkedFilePublicIDUnprocessableEntity) Error() string {
	return fmt.Sprintf("[PUT /api/v3/linked-files/{linked-file-public-id}][%d] putApiV3LinkedFilesLinkedFilePublicIdUnprocessableEntity ", 422)
}

func (o *PutAPIV3LinkedFilesLinkedFilePublicIDUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
