// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/bateau-eng/chapi/pkg/models"
)

// PutAPIV3MilestonesMilestonePublicIDReader is a Reader for the PutAPIV3MilestonesMilestonePublicID structure.
type PutAPIV3MilestonesMilestonePublicIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutAPIV3MilestonesMilestonePublicIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPutAPIV3MilestonesMilestonePublicIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPutAPIV3MilestonesMilestonePublicIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPutAPIV3MilestonesMilestonePublicIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewPutAPIV3MilestonesMilestonePublicIDUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPutAPIV3MilestonesMilestonePublicIDOK creates a PutAPIV3MilestonesMilestonePublicIDOK with default headers values
func NewPutAPIV3MilestonesMilestonePublicIDOK() *PutAPIV3MilestonesMilestonePublicIDOK {
	return &PutAPIV3MilestonesMilestonePublicIDOK{}
}

/*PutAPIV3MilestonesMilestonePublicIDOK handles this case with default header values.

Resource
*/
type PutAPIV3MilestonesMilestonePublicIDOK struct {
	Payload *models.Milestone
}

func (o *PutAPIV3MilestonesMilestonePublicIDOK) Error() string {
	return fmt.Sprintf("[PUT /api/v3/milestones/{milestone-public-id}][%d] putApiV3MilestonesMilestonePublicIdOK  %+v", 200, o.Payload)
}

func (o *PutAPIV3MilestonesMilestonePublicIDOK) GetPayload() *models.Milestone {
	return o.Payload
}

func (o *PutAPIV3MilestonesMilestonePublicIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Milestone)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutAPIV3MilestonesMilestonePublicIDBadRequest creates a PutAPIV3MilestonesMilestonePublicIDBadRequest with default headers values
func NewPutAPIV3MilestonesMilestonePublicIDBadRequest() *PutAPIV3MilestonesMilestonePublicIDBadRequest {
	return &PutAPIV3MilestonesMilestonePublicIDBadRequest{}
}

/*PutAPIV3MilestonesMilestonePublicIDBadRequest handles this case with default header values.

Schema mismatch
*/
type PutAPIV3MilestonesMilestonePublicIDBadRequest struct {
}

func (o *PutAPIV3MilestonesMilestonePublicIDBadRequest) Error() string {
	return fmt.Sprintf("[PUT /api/v3/milestones/{milestone-public-id}][%d] putApiV3MilestonesMilestonePublicIdBadRequest ", 400)
}

func (o *PutAPIV3MilestonesMilestonePublicIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPutAPIV3MilestonesMilestonePublicIDNotFound creates a PutAPIV3MilestonesMilestonePublicIDNotFound with default headers values
func NewPutAPIV3MilestonesMilestonePublicIDNotFound() *PutAPIV3MilestonesMilestonePublicIDNotFound {
	return &PutAPIV3MilestonesMilestonePublicIDNotFound{}
}

/*PutAPIV3MilestonesMilestonePublicIDNotFound handles this case with default header values.

Resource does not exist
*/
type PutAPIV3MilestonesMilestonePublicIDNotFound struct {
}

func (o *PutAPIV3MilestonesMilestonePublicIDNotFound) Error() string {
	return fmt.Sprintf("[PUT /api/v3/milestones/{milestone-public-id}][%d] putApiV3MilestonesMilestonePublicIdNotFound ", 404)
}

func (o *PutAPIV3MilestonesMilestonePublicIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPutAPIV3MilestonesMilestonePublicIDUnprocessableEntity creates a PutAPIV3MilestonesMilestonePublicIDUnprocessableEntity with default headers values
func NewPutAPIV3MilestonesMilestonePublicIDUnprocessableEntity() *PutAPIV3MilestonesMilestonePublicIDUnprocessableEntity {
	return &PutAPIV3MilestonesMilestonePublicIDUnprocessableEntity{}
}

/*PutAPIV3MilestonesMilestonePublicIDUnprocessableEntity handles this case with default header values.

Unprocessable
*/
type PutAPIV3MilestonesMilestonePublicIDUnprocessableEntity struct {
}

func (o *PutAPIV3MilestonesMilestonePublicIDUnprocessableEntity) Error() string {
	return fmt.Sprintf("[PUT /api/v3/milestones/{milestone-public-id}][%d] putApiV3MilestonesMilestonePublicIdUnprocessableEntity ", 422)
}

func (o *PutAPIV3MilestonesMilestonePublicIDUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
