// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/bateau-eng/chapi/pkg/models"
)

// PutAPIV3EpicsEpicPublicIDCommentsCommentPublicIDReader is a Reader for the PutAPIV3EpicsEpicPublicIDCommentsCommentPublicID structure.
type PutAPIV3EpicsEpicPublicIDCommentsCommentPublicIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutAPIV3EpicsEpicPublicIDCommentsCommentPublicIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPutAPIV3EpicsEpicPublicIDCommentsCommentPublicIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPutAPIV3EpicsEpicPublicIDCommentsCommentPublicIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPutAPIV3EpicsEpicPublicIDCommentsCommentPublicIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewPutAPIV3EpicsEpicPublicIDCommentsCommentPublicIDUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPutAPIV3EpicsEpicPublicIDCommentsCommentPublicIDOK creates a PutAPIV3EpicsEpicPublicIDCommentsCommentPublicIDOK with default headers values
func NewPutAPIV3EpicsEpicPublicIDCommentsCommentPublicIDOK() *PutAPIV3EpicsEpicPublicIDCommentsCommentPublicIDOK {
	return &PutAPIV3EpicsEpicPublicIDCommentsCommentPublicIDOK{}
}

/*PutAPIV3EpicsEpicPublicIDCommentsCommentPublicIDOK handles this case with default header values.

Resource
*/
type PutAPIV3EpicsEpicPublicIDCommentsCommentPublicIDOK struct {
	Payload *models.ThreadedComment
}

func (o *PutAPIV3EpicsEpicPublicIDCommentsCommentPublicIDOK) Error() string {
	return fmt.Sprintf("[PUT /api/v3/epics/{epic-public-id}/comments/{comment-public-id}][%d] putApiV3EpicsEpicPublicIdCommentsCommentPublicIdOK  %+v", 200, o.Payload)
}

func (o *PutAPIV3EpicsEpicPublicIDCommentsCommentPublicIDOK) GetPayload() *models.ThreadedComment {
	return o.Payload
}

func (o *PutAPIV3EpicsEpicPublicIDCommentsCommentPublicIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ThreadedComment)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutAPIV3EpicsEpicPublicIDCommentsCommentPublicIDBadRequest creates a PutAPIV3EpicsEpicPublicIDCommentsCommentPublicIDBadRequest with default headers values
func NewPutAPIV3EpicsEpicPublicIDCommentsCommentPublicIDBadRequest() *PutAPIV3EpicsEpicPublicIDCommentsCommentPublicIDBadRequest {
	return &PutAPIV3EpicsEpicPublicIDCommentsCommentPublicIDBadRequest{}
}

/*PutAPIV3EpicsEpicPublicIDCommentsCommentPublicIDBadRequest handles this case with default header values.

Schema mismatch
*/
type PutAPIV3EpicsEpicPublicIDCommentsCommentPublicIDBadRequest struct {
}

func (o *PutAPIV3EpicsEpicPublicIDCommentsCommentPublicIDBadRequest) Error() string {
	return fmt.Sprintf("[PUT /api/v3/epics/{epic-public-id}/comments/{comment-public-id}][%d] putApiV3EpicsEpicPublicIdCommentsCommentPublicIdBadRequest ", 400)
}

func (o *PutAPIV3EpicsEpicPublicIDCommentsCommentPublicIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPutAPIV3EpicsEpicPublicIDCommentsCommentPublicIDNotFound creates a PutAPIV3EpicsEpicPublicIDCommentsCommentPublicIDNotFound with default headers values
func NewPutAPIV3EpicsEpicPublicIDCommentsCommentPublicIDNotFound() *PutAPIV3EpicsEpicPublicIDCommentsCommentPublicIDNotFound {
	return &PutAPIV3EpicsEpicPublicIDCommentsCommentPublicIDNotFound{}
}

/*PutAPIV3EpicsEpicPublicIDCommentsCommentPublicIDNotFound handles this case with default header values.

Resource does not exist
*/
type PutAPIV3EpicsEpicPublicIDCommentsCommentPublicIDNotFound struct {
}

func (o *PutAPIV3EpicsEpicPublicIDCommentsCommentPublicIDNotFound) Error() string {
	return fmt.Sprintf("[PUT /api/v3/epics/{epic-public-id}/comments/{comment-public-id}][%d] putApiV3EpicsEpicPublicIdCommentsCommentPublicIdNotFound ", 404)
}

func (o *PutAPIV3EpicsEpicPublicIDCommentsCommentPublicIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPutAPIV3EpicsEpicPublicIDCommentsCommentPublicIDUnprocessableEntity creates a PutAPIV3EpicsEpicPublicIDCommentsCommentPublicIDUnprocessableEntity with default headers values
func NewPutAPIV3EpicsEpicPublicIDCommentsCommentPublicIDUnprocessableEntity() *PutAPIV3EpicsEpicPublicIDCommentsCommentPublicIDUnprocessableEntity {
	return &PutAPIV3EpicsEpicPublicIDCommentsCommentPublicIDUnprocessableEntity{}
}

/*PutAPIV3EpicsEpicPublicIDCommentsCommentPublicIDUnprocessableEntity handles this case with default header values.

Unprocessable
*/
type PutAPIV3EpicsEpicPublicIDCommentsCommentPublicIDUnprocessableEntity struct {
}

func (o *PutAPIV3EpicsEpicPublicIDCommentsCommentPublicIDUnprocessableEntity) Error() string {
	return fmt.Sprintf("[PUT /api/v3/epics/{epic-public-id}/comments/{comment-public-id}][%d] putApiV3EpicsEpicPublicIdCommentsCommentPublicIdUnprocessableEntity ", 422)
}

func (o *PutAPIV3EpicsEpicPublicIDCommentsCommentPublicIDUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
