// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPutAPIV3EntityTemplatesEnableParams creates a new PutAPIV3EntityTemplatesEnableParams object
// with the default values initialized.
func NewPutAPIV3EntityTemplatesEnableParams() *PutAPIV3EntityTemplatesEnableParams {

	return &PutAPIV3EntityTemplatesEnableParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutAPIV3EntityTemplatesEnableParamsWithTimeout creates a new PutAPIV3EntityTemplatesEnableParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutAPIV3EntityTemplatesEnableParamsWithTimeout(timeout time.Duration) *PutAPIV3EntityTemplatesEnableParams {

	return &PutAPIV3EntityTemplatesEnableParams{

		timeout: timeout,
	}
}

// NewPutAPIV3EntityTemplatesEnableParamsWithContext creates a new PutAPIV3EntityTemplatesEnableParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutAPIV3EntityTemplatesEnableParamsWithContext(ctx context.Context) *PutAPIV3EntityTemplatesEnableParams {

	return &PutAPIV3EntityTemplatesEnableParams{

		Context: ctx,
	}
}

// NewPutAPIV3EntityTemplatesEnableParamsWithHTTPClient creates a new PutAPIV3EntityTemplatesEnableParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutAPIV3EntityTemplatesEnableParamsWithHTTPClient(client *http.Client) *PutAPIV3EntityTemplatesEnableParams {

	return &PutAPIV3EntityTemplatesEnableParams{
		HTTPClient: client,
	}
}

/*PutAPIV3EntityTemplatesEnableParams contains all the parameters to send to the API endpoint
for the put API v3 entity templates enable operation typically these are written to a http.Request
*/
type PutAPIV3EntityTemplatesEnableParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put API v3 entity templates enable params
func (o *PutAPIV3EntityTemplatesEnableParams) WithTimeout(timeout time.Duration) *PutAPIV3EntityTemplatesEnableParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put API v3 entity templates enable params
func (o *PutAPIV3EntityTemplatesEnableParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put API v3 entity templates enable params
func (o *PutAPIV3EntityTemplatesEnableParams) WithContext(ctx context.Context) *PutAPIV3EntityTemplatesEnableParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put API v3 entity templates enable params
func (o *PutAPIV3EntityTemplatesEnableParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put API v3 entity templates enable params
func (o *PutAPIV3EntityTemplatesEnableParams) WithHTTPClient(client *http.Client) *PutAPIV3EntityTemplatesEnableParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put API v3 entity templates enable params
func (o *PutAPIV3EntityTemplatesEnableParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *PutAPIV3EntityTemplatesEnableParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
