// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/bateau-eng/chapi/pkg/models"
)

// NewPutAPIV3EpicsEpicPublicIDParams creates a new PutAPIV3EpicsEpicPublicIDParams object
// with the default values initialized.
func NewPutAPIV3EpicsEpicPublicIDParams() *PutAPIV3EpicsEpicPublicIDParams {
	var ()
	return &PutAPIV3EpicsEpicPublicIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutAPIV3EpicsEpicPublicIDParamsWithTimeout creates a new PutAPIV3EpicsEpicPublicIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutAPIV3EpicsEpicPublicIDParamsWithTimeout(timeout time.Duration) *PutAPIV3EpicsEpicPublicIDParams {
	var ()
	return &PutAPIV3EpicsEpicPublicIDParams{

		timeout: timeout,
	}
}

// NewPutAPIV3EpicsEpicPublicIDParamsWithContext creates a new PutAPIV3EpicsEpicPublicIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutAPIV3EpicsEpicPublicIDParamsWithContext(ctx context.Context) *PutAPIV3EpicsEpicPublicIDParams {
	var ()
	return &PutAPIV3EpicsEpicPublicIDParams{

		Context: ctx,
	}
}

// NewPutAPIV3EpicsEpicPublicIDParamsWithHTTPClient creates a new PutAPIV3EpicsEpicPublicIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutAPIV3EpicsEpicPublicIDParamsWithHTTPClient(client *http.Client) *PutAPIV3EpicsEpicPublicIDParams {
	var ()
	return &PutAPIV3EpicsEpicPublicIDParams{
		HTTPClient: client,
	}
}

/*PutAPIV3EpicsEpicPublicIDParams contains all the parameters to send to the API endpoint
for the put API v3 epics epic public ID operation typically these are written to a http.Request
*/
type PutAPIV3EpicsEpicPublicIDParams struct {

	/*UpdateEpic*/
	UpdateEpic *models.UpdateEpic
	/*EpicPublicID
	  The unique ID of the Epic.

	*/
	EpicPublicID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put API v3 epics epic public ID params
func (o *PutAPIV3EpicsEpicPublicIDParams) WithTimeout(timeout time.Duration) *PutAPIV3EpicsEpicPublicIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put API v3 epics epic public ID params
func (o *PutAPIV3EpicsEpicPublicIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put API v3 epics epic public ID params
func (o *PutAPIV3EpicsEpicPublicIDParams) WithContext(ctx context.Context) *PutAPIV3EpicsEpicPublicIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put API v3 epics epic public ID params
func (o *PutAPIV3EpicsEpicPublicIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put API v3 epics epic public ID params
func (o *PutAPIV3EpicsEpicPublicIDParams) WithHTTPClient(client *http.Client) *PutAPIV3EpicsEpicPublicIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put API v3 epics epic public ID params
func (o *PutAPIV3EpicsEpicPublicIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUpdateEpic adds the updateEpic to the put API v3 epics epic public ID params
func (o *PutAPIV3EpicsEpicPublicIDParams) WithUpdateEpic(updateEpic *models.UpdateEpic) *PutAPIV3EpicsEpicPublicIDParams {
	o.SetUpdateEpic(updateEpic)
	return o
}

// SetUpdateEpic adds the updateEpic to the put API v3 epics epic public ID params
func (o *PutAPIV3EpicsEpicPublicIDParams) SetUpdateEpic(updateEpic *models.UpdateEpic) {
	o.UpdateEpic = updateEpic
}

// WithEpicPublicID adds the epicPublicID to the put API v3 epics epic public ID params
func (o *PutAPIV3EpicsEpicPublicIDParams) WithEpicPublicID(epicPublicID int64) *PutAPIV3EpicsEpicPublicIDParams {
	o.SetEpicPublicID(epicPublicID)
	return o
}

// SetEpicPublicID adds the epicPublicId to the put API v3 epics epic public ID params
func (o *PutAPIV3EpicsEpicPublicIDParams) SetEpicPublicID(epicPublicID int64) {
	o.EpicPublicID = epicPublicID
}

// WriteToRequest writes these params to a swagger request
func (o *PutAPIV3EpicsEpicPublicIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.UpdateEpic != nil {
		if err := r.SetBodyParam(o.UpdateEpic); err != nil {
			return err
		}
	}

	// path param epic-public-id
	if err := r.SetPathParam("epic-public-id", swag.FormatInt64(o.EpicPublicID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
