// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/bateau-eng/chapi/pkg/models"
)

// PutAPIV3GroupsGroupPublicIDReader is a Reader for the PutAPIV3GroupsGroupPublicID structure.
type PutAPIV3GroupsGroupPublicIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutAPIV3GroupsGroupPublicIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPutAPIV3GroupsGroupPublicIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPutAPIV3GroupsGroupPublicIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPutAPIV3GroupsGroupPublicIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewPutAPIV3GroupsGroupPublicIDUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPutAPIV3GroupsGroupPublicIDOK creates a PutAPIV3GroupsGroupPublicIDOK with default headers values
func NewPutAPIV3GroupsGroupPublicIDOK() *PutAPIV3GroupsGroupPublicIDOK {
	return &PutAPIV3GroupsGroupPublicIDOK{}
}

/*PutAPIV3GroupsGroupPublicIDOK handles this case with default header values.

Resource
*/
type PutAPIV3GroupsGroupPublicIDOK struct {
	Payload *models.Group
}

func (o *PutAPIV3GroupsGroupPublicIDOK) Error() string {
	return fmt.Sprintf("[PUT /api/v3/groups/{group-public-id}][%d] putApiV3GroupsGroupPublicIdOK  %+v", 200, o.Payload)
}

func (o *PutAPIV3GroupsGroupPublicIDOK) GetPayload() *models.Group {
	return o.Payload
}

func (o *PutAPIV3GroupsGroupPublicIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Group)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutAPIV3GroupsGroupPublicIDBadRequest creates a PutAPIV3GroupsGroupPublicIDBadRequest with default headers values
func NewPutAPIV3GroupsGroupPublicIDBadRequest() *PutAPIV3GroupsGroupPublicIDBadRequest {
	return &PutAPIV3GroupsGroupPublicIDBadRequest{}
}

/*PutAPIV3GroupsGroupPublicIDBadRequest handles this case with default header values.

Schema mismatch
*/
type PutAPIV3GroupsGroupPublicIDBadRequest struct {
}

func (o *PutAPIV3GroupsGroupPublicIDBadRequest) Error() string {
	return fmt.Sprintf("[PUT /api/v3/groups/{group-public-id}][%d] putApiV3GroupsGroupPublicIdBadRequest ", 400)
}

func (o *PutAPIV3GroupsGroupPublicIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPutAPIV3GroupsGroupPublicIDNotFound creates a PutAPIV3GroupsGroupPublicIDNotFound with default headers values
func NewPutAPIV3GroupsGroupPublicIDNotFound() *PutAPIV3GroupsGroupPublicIDNotFound {
	return &PutAPIV3GroupsGroupPublicIDNotFound{}
}

/*PutAPIV3GroupsGroupPublicIDNotFound handles this case with default header values.

Resource does not exist
*/
type PutAPIV3GroupsGroupPublicIDNotFound struct {
}

func (o *PutAPIV3GroupsGroupPublicIDNotFound) Error() string {
	return fmt.Sprintf("[PUT /api/v3/groups/{group-public-id}][%d] putApiV3GroupsGroupPublicIdNotFound ", 404)
}

func (o *PutAPIV3GroupsGroupPublicIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPutAPIV3GroupsGroupPublicIDUnprocessableEntity creates a PutAPIV3GroupsGroupPublicIDUnprocessableEntity with default headers values
func NewPutAPIV3GroupsGroupPublicIDUnprocessableEntity() *PutAPIV3GroupsGroupPublicIDUnprocessableEntity {
	return &PutAPIV3GroupsGroupPublicIDUnprocessableEntity{}
}

/*PutAPIV3GroupsGroupPublicIDUnprocessableEntity handles this case with default header values.

Unprocessable
*/
type PutAPIV3GroupsGroupPublicIDUnprocessableEntity struct {
}

func (o *PutAPIV3GroupsGroupPublicIDUnprocessableEntity) Error() string {
	return fmt.Sprintf("[PUT /api/v3/groups/{group-public-id}][%d] putApiV3GroupsGroupPublicIdUnprocessableEntity ", 422)
}

func (o *PutAPIV3GroupsGroupPublicIDUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
