// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/bateau-eng/chapi/pkg/models"
)

// NewPutAPIV3FilesFilePublicIDParams creates a new PutAPIV3FilesFilePublicIDParams object
// with the default values initialized.
func NewPutAPIV3FilesFilePublicIDParams() *PutAPIV3FilesFilePublicIDParams {
	var ()
	return &PutAPIV3FilesFilePublicIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutAPIV3FilesFilePublicIDParamsWithTimeout creates a new PutAPIV3FilesFilePublicIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutAPIV3FilesFilePublicIDParamsWithTimeout(timeout time.Duration) *PutAPIV3FilesFilePublicIDParams {
	var ()
	return &PutAPIV3FilesFilePublicIDParams{

		timeout: timeout,
	}
}

// NewPutAPIV3FilesFilePublicIDParamsWithContext creates a new PutAPIV3FilesFilePublicIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutAPIV3FilesFilePublicIDParamsWithContext(ctx context.Context) *PutAPIV3FilesFilePublicIDParams {
	var ()
	return &PutAPIV3FilesFilePublicIDParams{

		Context: ctx,
	}
}

// NewPutAPIV3FilesFilePublicIDParamsWithHTTPClient creates a new PutAPIV3FilesFilePublicIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutAPIV3FilesFilePublicIDParamsWithHTTPClient(client *http.Client) *PutAPIV3FilesFilePublicIDParams {
	var ()
	return &PutAPIV3FilesFilePublicIDParams{
		HTTPClient: client,
	}
}

/*PutAPIV3FilesFilePublicIDParams contains all the parameters to send to the API endpoint
for the put API v3 files file public ID operation typically these are written to a http.Request
*/
type PutAPIV3FilesFilePublicIDParams struct {

	/*UpdateFile*/
	UpdateFile *models.UpdateFile
	/*FilePublicID
	  The unique ID assigned to the file in Clubhouse.

	*/
	FilePublicID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put API v3 files file public ID params
func (o *PutAPIV3FilesFilePublicIDParams) WithTimeout(timeout time.Duration) *PutAPIV3FilesFilePublicIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put API v3 files file public ID params
func (o *PutAPIV3FilesFilePublicIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put API v3 files file public ID params
func (o *PutAPIV3FilesFilePublicIDParams) WithContext(ctx context.Context) *PutAPIV3FilesFilePublicIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put API v3 files file public ID params
func (o *PutAPIV3FilesFilePublicIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put API v3 files file public ID params
func (o *PutAPIV3FilesFilePublicIDParams) WithHTTPClient(client *http.Client) *PutAPIV3FilesFilePublicIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put API v3 files file public ID params
func (o *PutAPIV3FilesFilePublicIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUpdateFile adds the updateFile to the put API v3 files file public ID params
func (o *PutAPIV3FilesFilePublicIDParams) WithUpdateFile(updateFile *models.UpdateFile) *PutAPIV3FilesFilePublicIDParams {
	o.SetUpdateFile(updateFile)
	return o
}

// SetUpdateFile adds the updateFile to the put API v3 files file public ID params
func (o *PutAPIV3FilesFilePublicIDParams) SetUpdateFile(updateFile *models.UpdateFile) {
	o.UpdateFile = updateFile
}

// WithFilePublicID adds the filePublicID to the put API v3 files file public ID params
func (o *PutAPIV3FilesFilePublicIDParams) WithFilePublicID(filePublicID int64) *PutAPIV3FilesFilePublicIDParams {
	o.SetFilePublicID(filePublicID)
	return o
}

// SetFilePublicID adds the filePublicId to the put API v3 files file public ID params
func (o *PutAPIV3FilesFilePublicIDParams) SetFilePublicID(filePublicID int64) {
	o.FilePublicID = filePublicID
}

// WriteToRequest writes these params to a swagger request
func (o *PutAPIV3FilesFilePublicIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.UpdateFile != nil {
		if err := r.SetBodyParam(o.UpdateFile); err != nil {
			return err
		}
	}

	// path param file-public-id
	if err := r.SetPathParam("file-public-id", swag.FormatInt64(o.FilePublicID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
